// Code generated by ent, DO NOT EDIT.

package gatewayoperation

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the gatewayoperation type in the database.
	Label = "gateway_operation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldIdempotencyKeyHash holds the string denoting the idempotency_key_hash field in the database.
	FieldIdempotencyKeyHash = "idempotency_key_hash"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldReservedMicros holds the string denoting the reserved_micros field in the database.
	FieldReservedMicros = "reserved_micros"
	// FieldSettlementJSON holds the string denoting the settlement_json field in the database.
	FieldSettlementJSON = "settlement_json"
	// FieldFailureCode holds the string denoting the failure_code field in the database.
	FieldFailureCode = "failure_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// Table holds the table name of the gatewayoperation in the database.
	Table = "gateway_operations"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "gateway_operations"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "gateway_operations"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
)

// Columns holds all SQL columns for gatewayoperation fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldAPIKeyID,
	FieldIdempotencyKeyHash,
	FieldRequestHash,
	FieldEndpoint,
	FieldStatus,
	FieldReservedMicros,
	FieldSettlementJSON,
	FieldFailureCode,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IdempotencyKeyHashValidator is a validator for the "idempotency_key_hash" field. It is called by the builders before save.
	IdempotencyKeyHashValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// DefaultReservedMicros holds the default value on creation for the "reserved_micros" field.
	DefaultReservedMicros int64
	// ReservedMicrosValidator is a validator for the "reserved_micros" field. It is called by the builders before save.
	ReservedMicrosValidator func(int64) error
	// DefaultSettlementJSON holds the default value on creation for the "settlement_json" field.
	DefaultSettlementJSON string
	// DefaultFailureCode holds the default value on creation for the "failure_code" field.
	DefaultFailureCode string
	// FailureCodeValidator is a validator for the "failure_code" field. It is called by the builders before save.
	FailureCodeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Endpoint defines the type for the "endpoint" enum field.
type Endpoint string

// Endpoint values.
const (
	EndpointChatCompletions Endpoint = "chat_completions"
	EndpointResponses       Endpoint = "responses"
	EndpointMessages        Endpoint = "messages"
)

func (e Endpoint) String() string {
	return string(e)
}

// EndpointValidator is a validator for the "endpoint" field enum values. It is called by the builders before save.
func EndpointValidator(e Endpoint) error {
	switch e {
	case EndpointChatCompletions, EndpointResponses, EndpointMessages:
		return nil
	default:
		return fmt.Errorf("gatewayoperation: invalid enum value for endpoint field: %q", e)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusProcessing is the default value of the Status enum.
const DefaultStatus = StatusProcessing

// Status values.
const (
	StatusProcessing        Status = "processing"
	StatusPendingSettlement Status = "pending_settlement"
	StatusPendingUnknown    Status = "pending_unknown"
	StatusCompleted         Status = "completed"
	StatusFailed            Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusProcessing, StatusPendingSettlement, StatusPendingUnknown, StatusCompleted, StatusFailed:
		return nil
	default:
		return fmt.Errorf("gatewayoperation: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the GatewayOperation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByIdempotencyKeyHash orders the results by the idempotency_key_hash field.
func ByIdempotencyKeyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKeyHash, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReservedMicros orders the results by the reserved_micros field.
func ByReservedMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservedMicros, opts...).ToFunc()
}

// BySettlementJSON orders the results by the settlement_json field.
func BySettlementJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementJSON, opts...).ToFunc()
}

// ByFailureCode orders the results by the failure_code field.
func ByFailureCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
