// Code generated by ent, DO NOT EDIT.

package modelroute

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the modelroute type in the database.
	Label = "model_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldPublicName holds the string denoting the public_name field in the database.
	FieldPublicName = "public_name"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldUpstreamName holds the string denoting the upstream_name field in the database.
	FieldUpstreamName = "upstream_name"
	// FieldInputPriceMicros holds the string denoting the input_price_micros field in the database.
	FieldInputPriceMicros = "input_price_micros"
	// FieldOutputPriceMicros holds the string denoting the output_price_micros field in the database.
	FieldOutputPriceMicros = "output_price_micros"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// EdgeAPIUsages holds the string denoting the api_usages edge name in mutations.
	EdgeAPIUsages = "api_usages"
	// Table holds the table name of the modelroute in the database.
	Table = "model_routes"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "model_routes"
	// ProviderInverseTable is the table name for the Provider entity.
	// It exists in this package in order to avoid circular dependency with the "provider" package.
	ProviderInverseTable = "providers"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_id"
	// APIUsagesTable is the table that holds the api_usages relation/edge.
	APIUsagesTable = "api_usages"
	// APIUsagesInverseTable is the table name for the APIUsage entity.
	// It exists in this package in order to avoid circular dependency with the "apiusage" package.
	APIUsagesInverseTable = "api_usages"
	// APIUsagesColumn is the table column denoting the api_usages relation/edge.
	APIUsagesColumn = "model_route_id"
)

// Columns holds all SQL columns for modelroute fields.
var Columns = []string{
	FieldID,
	FieldProviderID,
	FieldPublicName,
	FieldDisplayName,
	FieldUpstreamName,
	FieldInputPriceMicros,
	FieldOutputPriceMicros,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PublicNameValidator is a validator for the "public_name" field. It is called by the builders before save.
	PublicNameValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// UpstreamNameValidator is a validator for the "upstream_name" field. It is called by the builders before save.
	UpstreamNameValidator func(string) error
	// InputPriceMicrosValidator is a validator for the "input_price_micros" field. It is called by the builders before save.
	InputPriceMicrosValidator func(int64) error
	// OutputPriceMicrosValidator is a validator for the "output_price_micros" field. It is called by the builders before save.
	OutputPriceMicrosValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("modelroute: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the ModelRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByPublicName orders the results by the public_name field.
func ByPublicName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicName, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByUpstreamName orders the results by the upstream_name field.
func ByUpstreamName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamName, opts...).ToFunc()
}

// ByInputPriceMicros orders the results by the input_price_micros field.
func ByInputPriceMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputPriceMicros, opts...).ToFunc()
}

// ByOutputPriceMicros orders the results by the output_price_micros field.
func ByOutputPriceMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputPriceMicros, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIUsagesCount orders the results by api_usages count.
func ByAPIUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIUsagesStep(), opts...)
	}
}

// ByAPIUsages orders the results by api_usages terms.
func ByAPIUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
func newAPIUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIUsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIUsagesTable, APIUsagesColumn),
	)
}
