// Code generated by ent, DO NOT EDIT.

package modelroute

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/novro-gateway/novro/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldID, id))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldProviderID, v))
}

// UpstreamModelID applies equality check predicate on the "upstream_model_id" field. It's identical to UpstreamModelIDEQ.
func UpstreamModelID(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldUpstreamModelID, v))
}

// BillingGroupID applies equality check predicate on the "billing_group_id" field. It's identical to BillingGroupIDEQ.
func BillingGroupID(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldBillingGroupID, v))
}

// PublicName applies equality check predicate on the "public_name" field. It's identical to PublicNameEQ.
func PublicName(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldPublicName, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldDisplayName, v))
}

// UpstreamName applies equality check predicate on the "upstream_name" field. It's identical to UpstreamNameEQ.
func UpstreamName(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldUpstreamName, v))
}

// InputPriceMicros applies equality check predicate on the "input_price_micros" field. It's identical to InputPriceMicrosEQ.
func InputPriceMicros(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldInputPriceMicros, v))
}

// OutputPriceMicros applies equality check predicate on the "output_price_micros" field. It's identical to OutputPriceMicrosEQ.
func OutputPriceMicros(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldOutputPriceMicros, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldDeletedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldProviderID, vs...))
}

// UpstreamModelIDEQ applies the EQ predicate on the "upstream_model_id" field.
func UpstreamModelIDEQ(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldUpstreamModelID, v))
}

// UpstreamModelIDNEQ applies the NEQ predicate on the "upstream_model_id" field.
func UpstreamModelIDNEQ(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldUpstreamModelID, v))
}

// UpstreamModelIDIn applies the In predicate on the "upstream_model_id" field.
func UpstreamModelIDIn(vs ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldUpstreamModelID, vs...))
}

// UpstreamModelIDNotIn applies the NotIn predicate on the "upstream_model_id" field.
func UpstreamModelIDNotIn(vs ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldUpstreamModelID, vs...))
}

// UpstreamModelIDIsNil applies the IsNil predicate on the "upstream_model_id" field.
func UpstreamModelIDIsNil() predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIsNull(FieldUpstreamModelID))
}

// UpstreamModelIDNotNil applies the NotNil predicate on the "upstream_model_id" field.
func UpstreamModelIDNotNil() predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotNull(FieldUpstreamModelID))
}

// BillingGroupIDEQ applies the EQ predicate on the "billing_group_id" field.
func BillingGroupIDEQ(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldBillingGroupID, v))
}

// BillingGroupIDNEQ applies the NEQ predicate on the "billing_group_id" field.
func BillingGroupIDNEQ(v uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldBillingGroupID, v))
}

// BillingGroupIDIn applies the In predicate on the "billing_group_id" field.
func BillingGroupIDIn(vs ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldBillingGroupID, vs...))
}

// BillingGroupIDNotIn applies the NotIn predicate on the "billing_group_id" field.
func BillingGroupIDNotIn(vs ...uuid.UUID) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldBillingGroupID, vs...))
}

// PublicNameEQ applies the EQ predicate on the "public_name" field.
func PublicNameEQ(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldPublicName, v))
}

// PublicNameNEQ applies the NEQ predicate on the "public_name" field.
func PublicNameNEQ(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldPublicName, v))
}

// PublicNameIn applies the In predicate on the "public_name" field.
func PublicNameIn(vs ...string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldPublicName, vs...))
}

// PublicNameNotIn applies the NotIn predicate on the "public_name" field.
func PublicNameNotIn(vs ...string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldPublicName, vs...))
}

// PublicNameGT applies the GT predicate on the "public_name" field.
func PublicNameGT(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldPublicName, v))
}

// PublicNameGTE applies the GTE predicate on the "public_name" field.
func PublicNameGTE(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldPublicName, v))
}

// PublicNameLT applies the LT predicate on the "public_name" field.
func PublicNameLT(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldPublicName, v))
}

// PublicNameLTE applies the LTE predicate on the "public_name" field.
func PublicNameLTE(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldPublicName, v))
}

// PublicNameContains applies the Contains predicate on the "public_name" field.
func PublicNameContains(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldContains(FieldPublicName, v))
}

// PublicNameHasPrefix applies the HasPrefix predicate on the "public_name" field.
func PublicNameHasPrefix(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldHasPrefix(FieldPublicName, v))
}

// PublicNameHasSuffix applies the HasSuffix predicate on the "public_name" field.
func PublicNameHasSuffix(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldHasSuffix(FieldPublicName, v))
}

// PublicNameEqualFold applies the EqualFold predicate on the "public_name" field.
func PublicNameEqualFold(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEqualFold(FieldPublicName, v))
}

// PublicNameContainsFold applies the ContainsFold predicate on the "public_name" field.
func PublicNameContainsFold(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldContainsFold(FieldPublicName, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldContainsFold(FieldDisplayName, v))
}

// UpstreamNameEQ applies the EQ predicate on the "upstream_name" field.
func UpstreamNameEQ(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldUpstreamName, v))
}

// UpstreamNameNEQ applies the NEQ predicate on the "upstream_name" field.
func UpstreamNameNEQ(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldUpstreamName, v))
}

// UpstreamNameIn applies the In predicate on the "upstream_name" field.
func UpstreamNameIn(vs ...string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldUpstreamName, vs...))
}

// UpstreamNameNotIn applies the NotIn predicate on the "upstream_name" field.
func UpstreamNameNotIn(vs ...string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldUpstreamName, vs...))
}

// UpstreamNameGT applies the GT predicate on the "upstream_name" field.
func UpstreamNameGT(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldUpstreamName, v))
}

// UpstreamNameGTE applies the GTE predicate on the "upstream_name" field.
func UpstreamNameGTE(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldUpstreamName, v))
}

// UpstreamNameLT applies the LT predicate on the "upstream_name" field.
func UpstreamNameLT(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldUpstreamName, v))
}

// UpstreamNameLTE applies the LTE predicate on the "upstream_name" field.
func UpstreamNameLTE(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldUpstreamName, v))
}

// UpstreamNameContains applies the Contains predicate on the "upstream_name" field.
func UpstreamNameContains(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldContains(FieldUpstreamName, v))
}

// UpstreamNameHasPrefix applies the HasPrefix predicate on the "upstream_name" field.
func UpstreamNameHasPrefix(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldHasPrefix(FieldUpstreamName, v))
}

// UpstreamNameHasSuffix applies the HasSuffix predicate on the "upstream_name" field.
func UpstreamNameHasSuffix(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldHasSuffix(FieldUpstreamName, v))
}

// UpstreamNameEqualFold applies the EqualFold predicate on the "upstream_name" field.
func UpstreamNameEqualFold(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEqualFold(FieldUpstreamName, v))
}

// UpstreamNameContainsFold applies the ContainsFold predicate on the "upstream_name" field.
func UpstreamNameContainsFold(v string) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldContainsFold(FieldUpstreamName, v))
}

// InputPriceMicrosEQ applies the EQ predicate on the "input_price_micros" field.
func InputPriceMicrosEQ(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldInputPriceMicros, v))
}

// InputPriceMicrosNEQ applies the NEQ predicate on the "input_price_micros" field.
func InputPriceMicrosNEQ(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldInputPriceMicros, v))
}

// InputPriceMicrosIn applies the In predicate on the "input_price_micros" field.
func InputPriceMicrosIn(vs ...int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldInputPriceMicros, vs...))
}

// InputPriceMicrosNotIn applies the NotIn predicate on the "input_price_micros" field.
func InputPriceMicrosNotIn(vs ...int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldInputPriceMicros, vs...))
}

// InputPriceMicrosGT applies the GT predicate on the "input_price_micros" field.
func InputPriceMicrosGT(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldInputPriceMicros, v))
}

// InputPriceMicrosGTE applies the GTE predicate on the "input_price_micros" field.
func InputPriceMicrosGTE(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldInputPriceMicros, v))
}

// InputPriceMicrosLT applies the LT predicate on the "input_price_micros" field.
func InputPriceMicrosLT(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldInputPriceMicros, v))
}

// InputPriceMicrosLTE applies the LTE predicate on the "input_price_micros" field.
func InputPriceMicrosLTE(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldInputPriceMicros, v))
}

// OutputPriceMicrosEQ applies the EQ predicate on the "output_price_micros" field.
func OutputPriceMicrosEQ(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldOutputPriceMicros, v))
}

// OutputPriceMicrosNEQ applies the NEQ predicate on the "output_price_micros" field.
func OutputPriceMicrosNEQ(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldOutputPriceMicros, v))
}

// OutputPriceMicrosIn applies the In predicate on the "output_price_micros" field.
func OutputPriceMicrosIn(vs ...int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldOutputPriceMicros, vs...))
}

// OutputPriceMicrosNotIn applies the NotIn predicate on the "output_price_micros" field.
func OutputPriceMicrosNotIn(vs ...int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldOutputPriceMicros, vs...))
}

// OutputPriceMicrosGT applies the GT predicate on the "output_price_micros" field.
func OutputPriceMicrosGT(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldOutputPriceMicros, v))
}

// OutputPriceMicrosGTE applies the GTE predicate on the "output_price_micros" field.
func OutputPriceMicrosGTE(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldOutputPriceMicros, v))
}

// OutputPriceMicrosLT applies the LT predicate on the "output_price_micros" field.
func OutputPriceMicrosLT(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldOutputPriceMicros, v))
}

// OutputPriceMicrosLTE applies the LTE predicate on the "output_price_micros" field.
func OutputPriceMicrosLTE(v int64) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldOutputPriceMicros, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ModelRoute {
	return predicate.ModelRoute(sql.FieldNotNull(FieldDeletedAt))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Provider) predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUpstreamModel applies the HasEdge predicate on the "upstream_model" edge.
func HasUpstreamModel() predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UpstreamModelTable, UpstreamModelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUpstreamModelWith applies the HasEdge predicate on the "upstream_model" edge with a given conditions (other predicates).
func HasUpstreamModelWith(preds ...predicate.UpstreamModel) predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := newUpstreamModelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBillingGroup applies the HasEdge predicate on the "billing_group" edge.
func HasBillingGroup() predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BillingGroupTable, BillingGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBillingGroupWith applies the HasEdge predicate on the "billing_group" edge with a given conditions (other predicates).
func HasBillingGroupWith(preds ...predicate.BillingGroup) predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := newBillingGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIUsages applies the HasEdge predicate on the "api_usages" edge.
func HasAPIUsages() predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIUsagesTable, APIUsagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIUsagesWith applies the HasEdge predicate on the "api_usages" edge with a given conditions (other predicates).
func HasAPIUsagesWith(preds ...predicate.APIUsage) predicate.ModelRoute {
	return predicate.ModelRoute(func(s *sql.Selector) {
		step := newAPIUsagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelRoute) predicate.ModelRoute {
	return predicate.ModelRoute(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelRoute) predicate.ModelRoute {
	return predicate.ModelRoute(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelRoute) predicate.ModelRoute {
	return predicate.ModelRoute(sql.NotPredicates(p))
}
