// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "key_prefix", Type: field.TypeString, Size: 16},
		{Name: "key_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "key_secret_ciphertext", Type: field.TypeString, Size: 256, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "revoked"}, Default: "active"},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "billing_group_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_keys_billing_groups_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[9]},
				RefColumns: []*schema.Column{BillingGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_keys_users_api_keys",
				Columns:    []*schema.Column{APIKeysColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_user_id_status",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[10], APIKeysColumns[5]},
			},
			{
				Name:    "apikey_billing_group_id_status",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[9], APIKeysColumns[5]},
			},
			{
				Name:    "apikey_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[5], APIKeysColumns[7]},
			},
		},
	}
	// APIUsagesColumns holds the columns for the "api_usages" table.
	APIUsagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "request_id", Type: field.TypeUUID, Unique: true},
		{Name: "endpoint", Type: field.TypeEnum, Enums: []string{"chat_completions", "responses", "messages"}},
		{Name: "status_code", Type: field.TypeInt, Default: 200},
		{Name: "error_code", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "error_message", Type: field.TypeString, Size: 1024, Default: ""},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "uncached_input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_read_input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_write_input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cache_write_1h_input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "input_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "output_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "cache_read_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "cache_write_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "cache_write_1h_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "request_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "base_cost_micros", Type: field.TypeInt64, Default: 0},
		{Name: "multiplier_bps", Type: field.TypeInt64, Default: 10000},
		{Name: "cost_micros", Type: field.TypeInt64, Default: 0},
		{Name: "reserved_micros", Type: field.TypeInt64, Default: 0},
		{Name: "estimated", Type: field.TypeBool, Default: false},
		{Name: "upstream_request_id", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "model_name", Type: field.TypeString, Size: 256, Default: ""},
		{Name: "upstream_model_name", Type: field.TypeString, Size: 256, Default: ""},
		{Name: "billing_group_code", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "billing_group_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "calculation_version", Type: field.TypeString, Size: 32, Default: "v1"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "api_key_id", Type: field.TypeUUID},
		{Name: "billing_group_id", Type: field.TypeUUID, Nullable: true},
		{Name: "model_route_id", Type: field.TypeUUID},
		{Name: "upstream_model_id", Type: field.TypeUUID, Nullable: true},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// APIUsagesTable holds the schema information for the "api_usages" table.
	APIUsagesTable = &schema.Table{
		Name:       "api_usages",
		Columns:    APIUsagesColumns,
		PrimaryKey: []*schema.Column{APIUsagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "api_usages_api_keys_api_usages",
				Columns:    []*schema.Column{APIUsagesColumns[32]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_usages_billing_groups_api_usages",
				Columns:    []*schema.Column{APIUsagesColumns[33]},
				RefColumns: []*schema.Column{BillingGroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_usages_model_routes_api_usages",
				Columns:    []*schema.Column{APIUsagesColumns[34]},
				RefColumns: []*schema.Column{ModelRoutesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "api_usages_upstream_models_api_usages",
				Columns:    []*schema.Column{APIUsagesColumns[35]},
				RefColumns: []*schema.Column{UpstreamModelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "api_usages_users_api_usages",
				Columns:    []*schema.Column{APIUsagesColumns[36]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "apiusage_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIUsagesColumns[36], APIUsagesColumns[29]},
			},
			{
				Name:    "apiusage_user_id_model_name_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIUsagesColumns[36], APIUsagesColumns[24], APIUsagesColumns[29]},
			},
			{
				Name:    "apiusage_user_id_status_code_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIUsagesColumns[36], APIUsagesColumns[3], APIUsagesColumns[29]},
			},
			{
				Name:    "apiusage_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIUsagesColumns[32], APIUsagesColumns[29]},
			},
			{
				Name:    "apiusage_model_route_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIUsagesColumns[34], APIUsagesColumns[29]},
			},
			{
				Name:    "apiusage_upstream_model_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIUsagesColumns[35], APIUsagesColumns[29]},
			},
			{
				Name:    "apiusage_billing_group_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{APIUsagesColumns[33], APIUsagesColumns[29]},
			},
		},
	}
	// BillingGroupsColumns holds the columns for the "billing_groups" table.
	BillingGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "display_name", Type: field.TypeString, Size: 128},
		{Name: "multiplier_bps", Type: field.TypeInt64, Default: 10000},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "is_hidden", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// BillingGroupsTable holds the schema information for the "billing_groups" table.
	BillingGroupsTable = &schema.Table{
		Name:       "billing_groups",
		Columns:    BillingGroupsColumns,
		PrimaryKey: []*schema.Column{BillingGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "billinggroup_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{BillingGroupsColumns[6], BillingGroupsColumns[7]},
			},
			{
				Name:    "billinggroup_is_default",
				Unique:  false,
				Columns: []*schema.Column{BillingGroupsColumns[4]},
			},
			{
				Name:    "billinggroup_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{BillingGroupsColumns[9]},
			},
		},
	}
	// EmailSMTPConfigsColumns holds the columns for the "email_smtp_configs" table.
	EmailSMTPConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 32},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "host", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "port", Type: field.TypeInt, Default: 587},
		{Name: "username", Type: field.TypeString, Size: 320, Default: ""},
		{Name: "encrypted_password", Type: field.TypeString, Size: 2048, Default: ""},
		{Name: "from_address", Type: field.TypeString, Size: 320, Default: ""},
		{Name: "security", Type: field.TypeString, Size: 16, Default: "starttls"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EmailSMTPConfigsTable holds the schema information for the "email_smtp_configs" table.
	EmailSMTPConfigsTable = &schema.Table{
		Name:       "email_smtp_configs",
		Columns:    EmailSMTPConfigsColumns,
		PrimaryKey: []*schema.Column{EmailSMTPConfigsColumns[0]},
	}
	// EmailVerificationCodesColumns holds the columns for the "email_verification_codes" table.
	EmailVerificationCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Size: 320},
		{Name: "code_hash", Type: field.TypeString, Size: 64},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "consumed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// EmailVerificationCodesTable holds the schema information for the "email_verification_codes" table.
	EmailVerificationCodesTable = &schema.Table{
		Name:       "email_verification_codes",
		Columns:    EmailVerificationCodesColumns,
		PrimaryKey: []*schema.Column{EmailVerificationCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "emailverificationcode_email",
				Unique:  true,
				Columns: []*schema.Column{EmailVerificationCodesColumns[1]},
			},
		},
	}
	// GatewayOperationsColumns holds the columns for the "gateway_operations" table.
	GatewayOperationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "idempotency_key_hash", Type: field.TypeString, Size: 64},
		{Name: "request_hash", Type: field.TypeString, Size: 64},
		{Name: "endpoint", Type: field.TypeEnum, Enums: []string{"chat_completions", "responses", "messages"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"processing", "pending_settlement", "pending_unknown", "completed", "failed"}, Default: "processing"},
		{Name: "reserved_micros", Type: field.TypeInt64, Default: 0},
		{Name: "settlement_json", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "failure_code", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "api_key_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// GatewayOperationsTable holds the schema information for the "gateway_operations" table.
	GatewayOperationsTable = &schema.Table{
		Name:       "gateway_operations",
		Columns:    GatewayOperationsColumns,
		PrimaryKey: []*schema.Column{GatewayOperationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "gateway_operations_api_keys_gateway_operations",
				Columns:    []*schema.Column{GatewayOperationsColumns[10]},
				RefColumns: []*schema.Column{APIKeysColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "gateway_operations_users_gateway_operations",
				Columns:    []*schema.Column{GatewayOperationsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "gatewayoperation_api_key_id_idempotency_key_hash",
				Unique:  true,
				Columns: []*schema.Column{GatewayOperationsColumns[10], GatewayOperationsColumns[1]},
			},
			{
				Name:    "gatewayoperation_status_updated_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayOperationsColumns[4], GatewayOperationsColumns[9]},
			},
			{
				Name:    "gatewayoperation_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{GatewayOperationsColumns[11], GatewayOperationsColumns[8]},
			},
		},
	}
	// ModelRoutesColumns holds the columns for the "model_routes" table.
	ModelRoutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "public_name", Type: field.TypeString, Size: 256},
		{Name: "display_name", Type: field.TypeString, Size: 128},
		{Name: "upstream_name", Type: field.TypeString, Size: 256},
		{Name: "input_price_micros", Type: field.TypeInt64},
		{Name: "output_price_micros", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "provider_id", Type: field.TypeUUID},
		{Name: "upstream_model_id", Type: field.TypeUUID, Nullable: true},
	}
	// ModelRoutesTable holds the schema information for the "model_routes" table.
	ModelRoutesTable = &schema.Table{
		Name:       "model_routes",
		Columns:    ModelRoutesColumns,
		PrimaryKey: []*schema.Column{ModelRoutesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "model_routes_providers_model_routes",
				Columns:    []*schema.Column{ModelRoutesColumns[10]},
				RefColumns: []*schema.Column{ProvidersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "model_routes_upstream_models_model_routes",
				Columns:    []*schema.Column{ModelRoutesColumns[11]},
				RefColumns: []*schema.Column{UpstreamModelsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "modelroute_public_name_provider_id_upstream_model_id",
				Unique:  true,
				Columns: []*schema.Column{ModelRoutesColumns[1], ModelRoutesColumns[10], ModelRoutesColumns[11]},
			},
			{
				Name:    "modelroute_provider_id_status",
				Unique:  false,
				Columns: []*schema.Column{ModelRoutesColumns[10], ModelRoutesColumns[6]},
			},
			{
				Name:    "modelroute_upstream_model_id_status",
				Unique:  false,
				Columns: []*schema.Column{ModelRoutesColumns[11], ModelRoutesColumns[6]},
			},
			{
				Name:    "modelroute_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{ModelRoutesColumns[6], ModelRoutesColumns[7]},
			},
			{
				Name:    "modelroute_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{ModelRoutesColumns[9]},
			},
		},
	}
	// PaymentConfigsColumns holds the columns for the "payment_configs" table.
	PaymentConfigsColumns = []*schema.Column{
		{Name: "provider", Type: field.TypeString, Size: 32},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "api_url", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "merchant_id", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "encrypted_merchant_key", Type: field.TypeString, Size: 2048, Default: ""},
		{Name: "site_name", Type: field.TypeString, Size: 64, Default: "Novro"},
		{Name: "channels", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "methods_json", Type: field.TypeString, Size: 2147483647, Default: "[]"},
		{Name: "min_top_up_micros", Type: field.TypeInt64, Default: 10000},
		{Name: "max_top_up_micros", Type: field.TypeInt64, Default: 50000000000},
		{Name: "preset_amounts_json", Type: field.TypeString, Size: 2147483647, Default: "[10000000,50000000,100000000,500000000]"},
		{Name: "bonus_tiers_json", Type: field.TypeString, Size: 2147483647, Default: "[]"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PaymentConfigsTable holds the schema information for the "payment_configs" table.
	PaymentConfigsTable = &schema.Table{
		Name:       "payment_configs",
		Columns:    PaymentConfigsColumns,
		PrimaryKey: []*schema.Column{PaymentConfigsColumns[0]},
	}
	// ProvidersColumns holds the columns for the "providers" table.
	ProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "display_name", Type: field.TypeString, Size: 128},
		{Name: "protocol", Type: field.TypeEnum, Enums: []string{"openai", "anthropic"}},
		{Name: "base_url", Type: field.TypeString, Size: 512},
		{Name: "model_list_path", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "weight", Type: field.TypeInt, Default: 100},
		{Name: "encrypted_api_key", Type: field.TypeString, Size: 2048},
		{Name: "api_key_hint", Type: field.TypeString, Size: 8},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "billing_group_id", Type: field.TypeUUID},
	}
	// ProvidersTable holds the schema information for the "providers" table.
	ProvidersTable = &schema.Table{
		Name:       "providers",
		Columns:    ProvidersColumns,
		PrimaryKey: []*schema.Column{ProvidersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "providers_billing_groups_providers",
				Columns:    []*schema.Column{ProvidersColumns[13]},
				RefColumns: []*schema.Column{BillingGroupsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "provider_billing_group_id_status",
				Unique:  false,
				Columns: []*schema.Column{ProvidersColumns[13], ProvidersColumns[9]},
			},
			{
				Name:    "provider_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{ProvidersColumns[9], ProvidersColumns[10]},
			},
			{
				Name:    "provider_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{ProvidersColumns[12]},
			},
		},
	}
	// SystemSettingsColumns holds the columns for the "system_settings" table.
	SystemSettingsColumns = []*schema.Column{
		{Name: "key", Type: field.TypeString, Size: 128},
		{Name: "value", Type: field.TypeString, Size: 1024, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemSettingsTable holds the schema information for the "system_settings" table.
	SystemSettingsTable = &schema.Table{
		Name:       "system_settings",
		Columns:    SystemSettingsColumns,
		PrimaryKey: []*schema.Column{SystemSettingsColumns[0]},
	}
	// TopUpOrdersColumns holds the columns for the "top_up_orders" table.
	TopUpOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "out_trade_no", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "provider", Type: field.TypeEnum, Enums: []string{"epay"}, Default: "epay"},
		{Name: "channel", Type: field.TypeString, Size: 32},
		{Name: "amount_micros", Type: field.TypeInt64},
		{Name: "credited_micros", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "paid"}, Default: "pending"},
		{Name: "provider_trade_no", Type: field.TypeString, Unique: true, Nullable: true, Size: 128},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// TopUpOrdersTable holds the schema information for the "top_up_orders" table.
	TopUpOrdersTable = &schema.Table{
		Name:       "top_up_orders",
		Columns:    TopUpOrdersColumns,
		PrimaryKey: []*schema.Column{TopUpOrdersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "top_up_orders_users_top_up_orders",
				Columns:    []*schema.Column{TopUpOrdersColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "topuporder_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TopUpOrdersColumns[11], TopUpOrdersColumns[9]},
			},
			{
				Name:    "topuporder_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{TopUpOrdersColumns[6], TopUpOrdersColumns[9]},
			},
		},
	}
	// UpstreamModelsColumns holds the columns for the "upstream_models" table.
	UpstreamModelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "provider_name", Type: field.TypeString, Size: 128},
		{Name: "upstream_name", Type: field.TypeString, Size: 256},
		{Name: "display_name", Type: field.TypeString, Size: 128},
		{Name: "input_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "output_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "cache_read_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "cache_write_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "cache_write_1h_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "request_price_micros", Type: field.TypeInt64, Default: 0},
		{Name: "pricing_configured", Type: field.TypeBool, Default: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UpstreamModelsTable holds the schema information for the "upstream_models" table.
	UpstreamModelsTable = &schema.Table{
		Name:       "upstream_models",
		Columns:    UpstreamModelsColumns,
		PrimaryKey: []*schema.Column{UpstreamModelsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "upstreammodel_upstream_name",
				Unique:  true,
				Columns: []*schema.Column{UpstreamModelsColumns[2]},
			},
			{
				Name:    "upstreammodel_provider_name_status",
				Unique:  false,
				Columns: []*schema.Column{UpstreamModelsColumns[1], UpstreamModelsColumns[11]},
			},
			{
				Name:    "upstreammodel_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{UpstreamModelsColumns[11], UpstreamModelsColumns[12]},
			},
			{
				Name:    "upstreammodel_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UpstreamModelsColumns[14]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "invite_code", Type: field.TypeString, Unique: true, Size: 16},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true, Size: 320},
		{Name: "display_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "is_system_admin", Type: field.TypeBool, Default: false},
		{Name: "can_access_hidden_groups", Type: field.TypeBool, Default: false},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "member"}, Default: "member"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "disabled"}, Default: "active"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "referred_by_user_id", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_users_referrals",
				Columns:    []*schema.Column{UsersColumns[13]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_role_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[8], UsersColumns[9]},
			},
			{
				Name:    "user_referred_by_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[13], UsersColumns[11]},
			},
		},
	}
	// UserIdentitiesColumns holds the columns for the "user_identities" table.
	UserIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "issuer", Type: field.TypeString, Size: 512},
		{Name: "subject", Type: field.TypeString, Size: 255},
		{Name: "email", Type: field.TypeString, Size: 320, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// UserIdentitiesTable holds the schema information for the "user_identities" table.
	UserIdentitiesTable = &schema.Table{
		Name:       "user_identities",
		Columns:    UserIdentitiesColumns,
		PrimaryKey: []*schema.Column{UserIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_identities_users_identities",
				Columns:    []*schema.Column{UserIdentitiesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "useridentity_issuer_subject",
				Unique:  true,
				Columns: []*schema.Column{UserIdentitiesColumns[1], UserIdentitiesColumns[2]},
			},
			{
				Name:    "useridentity_user_id_issuer",
				Unique:  true,
				Columns: []*schema.Column{UserIdentitiesColumns[6], UserIdentitiesColumns[1]},
			},
		},
	}
	// UserSessionsColumns holds the columns for the "user_sessions" table.
	UserSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
	}
	// UserSessionsTable holds the schema information for the "user_sessions" table.
	UserSessionsTable = &schema.Table{
		Name:       "user_sessions",
		Columns:    UserSessionsColumns,
		PrimaryKey: []*schema.Column{UserSessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_sessions_users_sessions",
				Columns:    []*schema.Column{UserSessionsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// WalletsColumns holds the columns for the "wallets" table.
	WalletsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "balance_micros", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID, Unique: true},
	}
	// WalletsTable holds the schema information for the "wallets" table.
	WalletsTable = &schema.Table{
		Name:       "wallets",
		Columns:    WalletsColumns,
		PrimaryKey: []*schema.Column{WalletsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wallets_users_wallet",
				Columns:    []*schema.Column{WalletsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// WalletEntriesColumns holds the columns for the "wallet_entries" table.
	WalletEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "reference_id", Type: field.TypeUUID},
		{Name: "entry_type", Type: field.TypeEnum, Enums: []string{"manual_adjustment", "top_up", "referral_reward", "usage_reservation", "usage_refund", "usage_settlement", "usage_compensation"}},
		{Name: "amount_micros", Type: field.TypeInt64},
		{Name: "balance_after_micros", Type: field.TypeInt64},
		{Name: "description", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "actor_user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "wallet_id", Type: field.TypeUUID},
	}
	// WalletEntriesTable holds the schema information for the "wallet_entries" table.
	WalletEntriesTable = &schema.Table{
		Name:       "wallet_entries",
		Columns:    WalletEntriesColumns,
		PrimaryKey: []*schema.Column{WalletEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wallet_entries_users_wallet_entries",
				Columns:    []*schema.Column{WalletEntriesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "wallet_entries_wallets_entries",
				Columns:    []*schema.Column{WalletEntriesColumns[8]},
				RefColumns: []*schema.Column{WalletsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "walletentry_wallet_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{WalletEntriesColumns[8], WalletEntriesColumns[6]},
			},
			{
				Name:    "walletentry_wallet_id_entry_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{WalletEntriesColumns[8], WalletEntriesColumns[2], WalletEntriesColumns[6]},
			},
			{
				Name:    "walletentry_reference_id",
				Unique:  false,
				Columns: []*schema.Column{WalletEntriesColumns[1]},
			},
			{
				Name:    "walletentry_wallet_id_reference_id_entry_type",
				Unique:  true,
				Columns: []*schema.Column{WalletEntriesColumns[8], WalletEntriesColumns[1], WalletEntriesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		APIUsagesTable,
		BillingGroupsTable,
		EmailSMTPConfigsTable,
		EmailVerificationCodesTable,
		GatewayOperationsTable,
		ModelRoutesTable,
		PaymentConfigsTable,
		ProvidersTable,
		SystemSettingsTable,
		TopUpOrdersTable,
		UpstreamModelsTable,
		UsersTable,
		UserIdentitiesTable,
		UserSessionsTable,
		WalletsTable,
		WalletEntriesTable,
	}
)

func init() {
	APIKeysTable.ForeignKeys[0].RefTable = BillingGroupsTable
	APIKeysTable.ForeignKeys[1].RefTable = UsersTable
	APIUsagesTable.ForeignKeys[0].RefTable = APIKeysTable
	APIUsagesTable.ForeignKeys[1].RefTable = BillingGroupsTable
	APIUsagesTable.ForeignKeys[2].RefTable = ModelRoutesTable
	APIUsagesTable.ForeignKeys[3].RefTable = UpstreamModelsTable
	APIUsagesTable.ForeignKeys[4].RefTable = UsersTable
	GatewayOperationsTable.ForeignKeys[0].RefTable = APIKeysTable
	GatewayOperationsTable.ForeignKeys[1].RefTable = UsersTable
	ModelRoutesTable.ForeignKeys[0].RefTable = ProvidersTable
	ModelRoutesTable.ForeignKeys[1].RefTable = UpstreamModelsTable
	ProvidersTable.ForeignKeys[0].RefTable = BillingGroupsTable
	TopUpOrdersTable.ForeignKeys[0].RefTable = UsersTable
	UsersTable.ForeignKeys[0].RefTable = UsersTable
	UserIdentitiesTable.ForeignKeys[0].RefTable = UsersTable
	UserSessionsTable.ForeignKeys[0].RefTable = UsersTable
	WalletsTable.ForeignKeys[0].RefTable = UsersTable
	WalletEntriesTable.ForeignKeys[0].RefTable = UsersTable
	WalletEntriesTable.ForeignKeys[1].RefTable = WalletsTable
}
