// Code generated by ent, DO NOT EDIT.

package billinggroup

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the billinggroup type in the database.
	Label = "billing_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldMultiplierBps holds the string denoting the multiplier_bps field in the database.
	FieldMultiplierBps = "multiplier_bps"
	// FieldDiscountName holds the string denoting the discount_name field in the database.
	FieldDiscountName = "discount_name"
	// FieldDiscountMultiplierBps holds the string denoting the discount_multiplier_bps field in the database.
	FieldDiscountMultiplierBps = "discount_multiplier_bps"
	// FieldDiscountStartsAt holds the string denoting the discount_starts_at field in the database.
	FieldDiscountStartsAt = "discount_starts_at"
	// FieldDiscountEndsAt holds the string denoting the discount_ends_at field in the database.
	FieldDiscountEndsAt = "discount_ends_at"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldIsHidden holds the string denoting the is_hidden field in the database.
	FieldIsHidden = "is_hidden"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeAPIKeys holds the string denoting the api_keys edge name in mutations.
	EdgeAPIKeys = "api_keys"
	// EdgeModelRoutes holds the string denoting the model_routes edge name in mutations.
	EdgeModelRoutes = "model_routes"
	// EdgeAPIUsages holds the string denoting the api_usages edge name in mutations.
	EdgeAPIUsages = "api_usages"
	// EdgeAuthorizedUsers holds the string denoting the authorized_users edge name in mutations.
	EdgeAuthorizedUsers = "authorized_users"
	// Table holds the table name of the billinggroup in the database.
	Table = "billing_groups"
	// APIKeysTable is the table that holds the api_keys relation/edge.
	APIKeysTable = "api_keys"
	// APIKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeysInverseTable = "api_keys"
	// APIKeysColumn is the table column denoting the api_keys relation/edge.
	APIKeysColumn = "billing_group_id"
	// ModelRoutesTable is the table that holds the model_routes relation/edge.
	ModelRoutesTable = "model_routes"
	// ModelRoutesInverseTable is the table name for the ModelRoute entity.
	// It exists in this package in order to avoid circular dependency with the "modelroute" package.
	ModelRoutesInverseTable = "model_routes"
	// ModelRoutesColumn is the table column denoting the model_routes relation/edge.
	ModelRoutesColumn = "billing_group_id"
	// APIUsagesTable is the table that holds the api_usages relation/edge.
	APIUsagesTable = "api_usages"
	// APIUsagesInverseTable is the table name for the APIUsage entity.
	// It exists in this package in order to avoid circular dependency with the "apiusage" package.
	APIUsagesInverseTable = "api_usages"
	// APIUsagesColumn is the table column denoting the api_usages relation/edge.
	APIUsagesColumn = "billing_group_id"
	// AuthorizedUsersTable is the table that holds the authorized_users relation/edge. The primary key declared below.
	AuthorizedUsersTable = "billing_group_authorized_users"
	// AuthorizedUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorizedUsersInverseTable = "users"
)

// Columns holds all SQL columns for billinggroup fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldDisplayName,
	FieldMultiplierBps,
	FieldDiscountName,
	FieldDiscountMultiplierBps,
	FieldDiscountStartsAt,
	FieldDiscountEndsAt,
	FieldIsDefault,
	FieldIsHidden,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

var (
	// AuthorizedUsersPrimaryKey and AuthorizedUsersColumn2 are the table columns denoting the
	// primary key for the authorized_users relation (M2M).
	AuthorizedUsersPrimaryKey = []string{"billing_group_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultMultiplierBps holds the default value on creation for the "multiplier_bps" field.
	DefaultMultiplierBps int64
	// MultiplierBpsValidator is a validator for the "multiplier_bps" field. It is called by the builders before save.
	MultiplierBpsValidator func(int64) error
	// DefaultDiscountName holds the default value on creation for the "discount_name" field.
	DefaultDiscountName string
	// DiscountNameValidator is a validator for the "discount_name" field. It is called by the builders before save.
	DiscountNameValidator func(string) error
	// DefaultDiscountMultiplierBps holds the default value on creation for the "discount_multiplier_bps" field.
	DefaultDiscountMultiplierBps int64
	// DiscountMultiplierBpsValidator is a validator for the "discount_multiplier_bps" field. It is called by the builders before save.
	DiscountMultiplierBpsValidator func(int64) error
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault bool
	// DefaultIsHidden holds the default value on creation for the "is_hidden" field.
	DefaultIsHidden bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("billinggroup: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BillingGroup queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByMultiplierBps orders the results by the multiplier_bps field.
func ByMultiplierBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMultiplierBps, opts...).ToFunc()
}

// ByDiscountName orders the results by the discount_name field.
func ByDiscountName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountName, opts...).ToFunc()
}

// ByDiscountMultiplierBps orders the results by the discount_multiplier_bps field.
func ByDiscountMultiplierBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountMultiplierBps, opts...).ToFunc()
}

// ByDiscountStartsAt orders the results by the discount_starts_at field.
func ByDiscountStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountStartsAt, opts...).ToFunc()
}

// ByDiscountEndsAt orders the results by the discount_ends_at field.
func ByDiscountEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountEndsAt, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByIsHidden orders the results by the is_hidden field.
func ByIsHidden(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsHidden, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByAPIKeysCount orders the results by api_keys count.
func ByAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeysStep(), opts...)
	}
}

// ByAPIKeys orders the results by api_keys terms.
func ByAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByModelRoutesCount orders the results by model_routes count.
func ByModelRoutesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newModelRoutesStep(), opts...)
	}
}

// ByModelRoutes orders the results by model_routes terms.
func ByModelRoutes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelRoutesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAPIUsagesCount orders the results by api_usages count.
func ByAPIUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIUsagesStep(), opts...)
	}
}

// ByAPIUsages orders the results by api_usages terms.
func ByAPIUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAuthorizedUsersCount orders the results by authorized_users count.
func ByAuthorizedUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthorizedUsersStep(), opts...)
	}
}

// ByAuthorizedUsers orders the results by authorized_users terms.
func ByAuthorizedUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorizedUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
	)
}
func newModelRoutesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelRoutesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ModelRoutesTable, ModelRoutesColumn),
	)
}
func newAPIUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIUsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIUsagesTable, APIUsagesColumn),
	)
}
func newAuthorizedUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorizedUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, AuthorizedUsersTable, AuthorizedUsersPrimaryKey...),
	)
}
