// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/novro-gateway/novro/ent/billinggroup"
)

// BillingGroup is the model entity for the BillingGroup schema.
type BillingGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// MultiplierBps holds the value of the "multiplier_bps" field.
	MultiplierBps int64 `json:"multiplier_bps,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault bool `json:"is_default,omitempty"`
	// IsHidden holds the value of the "is_hidden" field.
	IsHidden bool `json:"is_hidden,omitempty"`
	// Status holds the value of the "status" field.
	Status billinggroup.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillingGroupQuery when eager-loading is set.
	Edges        BillingGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BillingGroupEdges holds the relations/edges for other nodes in the graph.
type BillingGroupEdges struct {
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// Providers holds the value of the providers edge.
	Providers []*Provider `json:"providers,omitempty"`
	// APIUsages holds the value of the api_usages edge.
	APIUsages []*APIUsage `json:"api_usages,omitempty"`
	// AuthorizedUsers holds the value of the authorized_users edge.
	AuthorizedUsers []*User `json:"authorized_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e BillingGroupEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[0] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// ProvidersOrErr returns the Providers value or an error if the edge
// was not loaded in eager-loading.
func (e BillingGroupEdges) ProvidersOrErr() ([]*Provider, error) {
	if e.loadedTypes[1] {
		return e.Providers, nil
	}
	return nil, &NotLoadedError{edge: "providers"}
}

// APIUsagesOrErr returns the APIUsages value or an error if the edge
// was not loaded in eager-loading.
func (e BillingGroupEdges) APIUsagesOrErr() ([]*APIUsage, error) {
	if e.loadedTypes[2] {
		return e.APIUsages, nil
	}
	return nil, &NotLoadedError{edge: "api_usages"}
}

// AuthorizedUsersOrErr returns the AuthorizedUsers value or an error if the edge
// was not loaded in eager-loading.
func (e BillingGroupEdges) AuthorizedUsersOrErr() ([]*User, error) {
	if e.loadedTypes[3] {
		return e.AuthorizedUsers, nil
	}
	return nil, &NotLoadedError{edge: "authorized_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillingGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billinggroup.FieldIsDefault, billinggroup.FieldIsHidden:
			values[i] = new(sql.NullBool)
		case billinggroup.FieldMultiplierBps:
			values[i] = new(sql.NullInt64)
		case billinggroup.FieldCode, billinggroup.FieldDisplayName, billinggroup.FieldStatus:
			values[i] = new(sql.NullString)
		case billinggroup.FieldCreatedAt, billinggroup.FieldUpdatedAt, billinggroup.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case billinggroup.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillingGroup fields.
func (_m *BillingGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billinggroup.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case billinggroup.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case billinggroup.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case billinggroup.FieldMultiplierBps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field multiplier_bps", values[i])
			} else if value.Valid {
				_m.MultiplierBps = value.Int64
			}
		case billinggroup.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		case billinggroup.FieldIsHidden:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_hidden", values[i])
			} else if value.Valid {
				_m.IsHidden = value.Bool
			}
		case billinggroup.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = billinggroup.Status(value.String)
			}
		case billinggroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billinggroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case billinggroup.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillingGroup.
// This includes values selected through modifiers, order, etc.
func (_m *BillingGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKeys queries the "api_keys" edge of the BillingGroup entity.
func (_m *BillingGroup) QueryAPIKeys() *APIKeyQuery {
	return NewBillingGroupClient(_m.config).QueryAPIKeys(_m)
}

// QueryProviders queries the "providers" edge of the BillingGroup entity.
func (_m *BillingGroup) QueryProviders() *ProviderQuery {
	return NewBillingGroupClient(_m.config).QueryProviders(_m)
}

// QueryAPIUsages queries the "api_usages" edge of the BillingGroup entity.
func (_m *BillingGroup) QueryAPIUsages() *APIUsageQuery {
	return NewBillingGroupClient(_m.config).QueryAPIUsages(_m)
}

// QueryAuthorizedUsers queries the "authorized_users" edge of the BillingGroup entity.
func (_m *BillingGroup) QueryAuthorizedUsers() *UserQuery {
	return NewBillingGroupClient(_m.config).QueryAuthorizedUsers(_m)
}

// Update returns a builder for updating this BillingGroup.
// Note that you need to call BillingGroup.Unwrap() before calling this method if this BillingGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillingGroup) Update() *BillingGroupUpdateOne {
	return NewBillingGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillingGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillingGroup) Unwrap() *BillingGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillingGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillingGroup) String() string {
	var builder strings.Builder
	builder.WriteString("BillingGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("multiplier_bps=")
	builder.WriteString(fmt.Sprintf("%v", _m.MultiplierBps))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteString(", ")
	builder.WriteString("is_hidden=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsHidden))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BillingGroups is a parsable slice of BillingGroup.
type BillingGroups []*BillingGroup
