// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/novro-gateway/novro/ent/emailsmtpconfig"
)

// EmailSMTPConfigCreate is the builder for creating a EmailSMTPConfig entity.
type EmailSMTPConfigCreate struct {
	config
	mutation *EmailSMTPConfigMutation
	hooks    []Hook
}

// SetEnabled sets the "enabled" field.
func (_c *EmailSMTPConfigCreate) SetEnabled(v bool) *EmailSMTPConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableEnabled(v *bool) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetHost sets the "host" field.
func (_c *EmailSMTPConfigCreate) SetHost(v string) *EmailSMTPConfigCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableHost(v *string) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetPort sets the "port" field.
func (_c *EmailSMTPConfigCreate) SetPort(v int) *EmailSMTPConfigCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillablePort(v *int) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetPort(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *EmailSMTPConfigCreate) SetUsername(v string) *EmailSMTPConfigCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableUsername(v *string) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetEncryptedPassword sets the "encrypted_password" field.
func (_c *EmailSMTPConfigCreate) SetEncryptedPassword(v string) *EmailSMTPConfigCreate {
	_c.mutation.SetEncryptedPassword(v)
	return _c
}

// SetNillableEncryptedPassword sets the "encrypted_password" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableEncryptedPassword(v *string) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetEncryptedPassword(*v)
	}
	return _c
}

// SetFromAddress sets the "from_address" field.
func (_c *EmailSMTPConfigCreate) SetFromAddress(v string) *EmailSMTPConfigCreate {
	_c.mutation.SetFromAddress(v)
	return _c
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableFromAddress(v *string) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetFromAddress(*v)
	}
	return _c
}

// SetSecurity sets the "security" field.
func (_c *EmailSMTPConfigCreate) SetSecurity(v string) *EmailSMTPConfigCreate {
	_c.mutation.SetSecurity(v)
	return _c
}

// SetNillableSecurity sets the "security" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableSecurity(v *string) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetSecurity(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailSMTPConfigCreate) SetCreatedAt(v time.Time) *EmailSMTPConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableCreatedAt(v *time.Time) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EmailSMTPConfigCreate) SetUpdatedAt(v time.Time) *EmailSMTPConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EmailSMTPConfigCreate) SetNillableUpdatedAt(v *time.Time) *EmailSMTPConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EmailSMTPConfigCreate) SetID(v string) *EmailSMTPConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the EmailSMTPConfigMutation object of the builder.
func (_c *EmailSMTPConfigCreate) Mutation() *EmailSMTPConfigMutation {
	return _c.mutation
}

// Save creates the EmailSMTPConfig in the database.
func (_c *EmailSMTPConfigCreate) Save(ctx context.Context) (*EmailSMTPConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailSMTPConfigCreate) SaveX(ctx context.Context) *EmailSMTPConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailSMTPConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailSMTPConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailSMTPConfigCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := emailsmtpconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Host(); !ok {
		v := emailsmtpconfig.DefaultHost
		_c.mutation.SetHost(v)
	}
	if _, ok := _c.mutation.Port(); !ok {
		v := emailsmtpconfig.DefaultPort
		_c.mutation.SetPort(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := emailsmtpconfig.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.EncryptedPassword(); !ok {
		v := emailsmtpconfig.DefaultEncryptedPassword
		_c.mutation.SetEncryptedPassword(v)
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		v := emailsmtpconfig.DefaultFromAddress
		_c.mutation.SetFromAddress(v)
	}
	if _, ok := _c.mutation.Security(); !ok {
		v := emailsmtpconfig.DefaultSecurity
		_c.mutation.SetSecurity(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := emailsmtpconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := emailsmtpconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailSMTPConfigCreate) check() error {
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "EmailSMTPConfig.enabled"`)}
	}
	if _, ok := _c.mutation.Host(); !ok {
		return &ValidationError{Name: "host", err: errors.New(`ent: missing required field "EmailSMTPConfig.host"`)}
	}
	if v, ok := _c.mutation.Host(); ok {
		if err := emailsmtpconfig.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "EmailSMTPConfig.host": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`ent: missing required field "EmailSMTPConfig.port"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "EmailSMTPConfig.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := emailsmtpconfig.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "EmailSMTPConfig.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedPassword(); !ok {
		return &ValidationError{Name: "encrypted_password", err: errors.New(`ent: missing required field "EmailSMTPConfig.encrypted_password"`)}
	}
	if v, ok := _c.mutation.EncryptedPassword(); ok {
		if err := emailsmtpconfig.EncryptedPasswordValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_password", err: fmt.Errorf(`ent: validator failed for field "EmailSMTPConfig.encrypted_password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		return &ValidationError{Name: "from_address", err: errors.New(`ent: missing required field "EmailSMTPConfig.from_address"`)}
	}
	if v, ok := _c.mutation.FromAddress(); ok {
		if err := emailsmtpconfig.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "EmailSMTPConfig.from_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Security(); !ok {
		return &ValidationError{Name: "security", err: errors.New(`ent: missing required field "EmailSMTPConfig.security"`)}
	}
	if v, ok := _c.mutation.Security(); ok {
		if err := emailsmtpconfig.SecurityValidator(v); err != nil {
			return &ValidationError{Name: "security", err: fmt.Errorf(`ent: validator failed for field "EmailSMTPConfig.security": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "EmailSMTPConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "EmailSMTPConfig.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := emailsmtpconfig.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "EmailSMTPConfig.id": %w`, err)}
		}
	}
	return nil
}

func (_c *EmailSMTPConfigCreate) sqlSave(ctx context.Context) (*EmailSMTPConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected EmailSMTPConfig.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailSMTPConfigCreate) createSpec() (*EmailSMTPConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &EmailSMTPConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(emailsmtpconfig.Table, sqlgraph.NewFieldSpec(emailsmtpconfig.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(emailsmtpconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(emailsmtpconfig.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(emailsmtpconfig.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(emailsmtpconfig.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.EncryptedPassword(); ok {
		_spec.SetField(emailsmtpconfig.FieldEncryptedPassword, field.TypeString, value)
		_node.EncryptedPassword = value
	}
	if value, ok := _c.mutation.FromAddress(); ok {
		_spec.SetField(emailsmtpconfig.FieldFromAddress, field.TypeString, value)
		_node.FromAddress = value
	}
	if value, ok := _c.mutation.Security(); ok {
		_spec.SetField(emailsmtpconfig.FieldSecurity, field.TypeString, value)
		_node.Security = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(emailsmtpconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(emailsmtpconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// EmailSMTPConfigCreateBulk is the builder for creating many EmailSMTPConfig entities in bulk.
type EmailSMTPConfigCreateBulk struct {
	config
	err      error
	builders []*EmailSMTPConfigCreate
}

// Save creates the EmailSMTPConfig entities in the database.
func (_c *EmailSMTPConfigCreateBulk) Save(ctx context.Context) ([]*EmailSMTPConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EmailSMTPConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailSMTPConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailSMTPConfigCreateBulk) SaveX(ctx context.Context) []*EmailSMTPConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailSMTPConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailSMTPConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
