// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/novro-gateway/novro/ent/emailverificationcode"
	"github.com/novro-gateway/novro/ent/predicate"
)

// EmailVerificationCodeDelete is the builder for deleting a EmailVerificationCode entity.
type EmailVerificationCodeDelete struct {
	config
	hooks    []Hook
	mutation *EmailVerificationCodeMutation
}

// Where appends a list predicates to the EmailVerificationCodeDelete builder.
func (_d *EmailVerificationCodeDelete) Where(ps ...predicate.EmailVerificationCode) *EmailVerificationCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EmailVerificationCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmailVerificationCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EmailVerificationCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(emailverificationcode.Table, sqlgraph.NewFieldSpec(emailverificationcode.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EmailVerificationCodeDeleteOne is the builder for deleting a single EmailVerificationCode entity.
type EmailVerificationCodeDeleteOne struct {
	_d *EmailVerificationCodeDelete
}

// Where appends a list predicates to the EmailVerificationCodeDelete builder.
func (_d *EmailVerificationCodeDeleteOne) Where(ps ...predicate.EmailVerificationCode) *EmailVerificationCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EmailVerificationCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{emailverificationcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EmailVerificationCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
