// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/novro-gateway/novro/ent/modelpriceplan"
	"github.com/novro-gateway/novro/ent/modelpricewindow"
)

// ModelPriceWindowCreate is the builder for creating a ModelPriceWindow entity.
type ModelPriceWindowCreate struct {
	config
	mutation *ModelPriceWindowMutation
	hooks    []Hook
}

// SetPricePlanID sets the "price_plan_id" field.
func (_c *ModelPriceWindowCreate) SetPricePlanID(v uuid.UUID) *ModelPriceWindowCreate {
	_c.mutation.SetPricePlanID(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *ModelPriceWindowCreate) SetLabel(v string) *ModelPriceWindowCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetWeekdayMask sets the "weekday_mask" field.
func (_c *ModelPriceWindowCreate) SetWeekdayMask(v int) *ModelPriceWindowCreate {
	_c.mutation.SetWeekdayMask(v)
	return _c
}

// SetStartMinute sets the "start_minute" field.
func (_c *ModelPriceWindowCreate) SetStartMinute(v int) *ModelPriceWindowCreate {
	_c.mutation.SetStartMinute(v)
	return _c
}

// SetEndMinute sets the "end_minute" field.
func (_c *ModelPriceWindowCreate) SetEndMinute(v int) *ModelPriceWindowCreate {
	_c.mutation.SetEndMinute(v)
	return _c
}

// SetInputPriceMicros sets the "input_price_micros" field.
func (_c *ModelPriceWindowCreate) SetInputPriceMicros(v int64) *ModelPriceWindowCreate {
	_c.mutation.SetInputPriceMicros(v)
	return _c
}

// SetOutputPriceMicros sets the "output_price_micros" field.
func (_c *ModelPriceWindowCreate) SetOutputPriceMicros(v int64) *ModelPriceWindowCreate {
	_c.mutation.SetOutputPriceMicros(v)
	return _c
}

// SetCacheReadPriceMicros sets the "cache_read_price_micros" field.
func (_c *ModelPriceWindowCreate) SetCacheReadPriceMicros(v int64) *ModelPriceWindowCreate {
	_c.mutation.SetCacheReadPriceMicros(v)
	return _c
}

// SetCacheWritePriceMicros sets the "cache_write_price_micros" field.
func (_c *ModelPriceWindowCreate) SetCacheWritePriceMicros(v int64) *ModelPriceWindowCreate {
	_c.mutation.SetCacheWritePriceMicros(v)
	return _c
}

// SetCacheWrite1hPriceMicros sets the "cache_write_1h_price_micros" field.
func (_c *ModelPriceWindowCreate) SetCacheWrite1hPriceMicros(v int64) *ModelPriceWindowCreate {
	_c.mutation.SetCacheWrite1hPriceMicros(v)
	return _c
}

// SetRequestPriceMicros sets the "request_price_micros" field.
func (_c *ModelPriceWindowCreate) SetRequestPriceMicros(v int64) *ModelPriceWindowCreate {
	_c.mutation.SetRequestPriceMicros(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelPriceWindowCreate) SetCreatedAt(v time.Time) *ModelPriceWindowCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelPriceWindowCreate) SetNillableCreatedAt(v *time.Time) *ModelPriceWindowCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelPriceWindowCreate) SetID(v uuid.UUID) *ModelPriceWindowCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ModelPriceWindowCreate) SetNillableID(v *uuid.UUID) *ModelPriceWindowCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPricePlan sets the "price_plan" edge to the ModelPricePlan entity.
func (_c *ModelPriceWindowCreate) SetPricePlan(v *ModelPricePlan) *ModelPriceWindowCreate {
	return _c.SetPricePlanID(v.ID)
}

// Mutation returns the ModelPriceWindowMutation object of the builder.
func (_c *ModelPriceWindowCreate) Mutation() *ModelPriceWindowMutation {
	return _c.mutation
}

// Save creates the ModelPriceWindow in the database.
func (_c *ModelPriceWindowCreate) Save(ctx context.Context) (*ModelPriceWindow, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelPriceWindowCreate) SaveX(ctx context.Context) *ModelPriceWindow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPriceWindowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPriceWindowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelPriceWindowCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelpricewindow.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := modelpricewindow.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelPriceWindowCreate) check() error {
	if _, ok := _c.mutation.PricePlanID(); !ok {
		return &ValidationError{Name: "price_plan_id", err: errors.New(`ent: missing required field "ModelPriceWindow.price_plan_id"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "ModelPriceWindow.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := modelpricewindow.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WeekdayMask(); !ok {
		return &ValidationError{Name: "weekday_mask", err: errors.New(`ent: missing required field "ModelPriceWindow.weekday_mask"`)}
	}
	if v, ok := _c.mutation.WeekdayMask(); ok {
		if err := modelpricewindow.WeekdayMaskValidator(v); err != nil {
			return &ValidationError{Name: "weekday_mask", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.weekday_mask": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartMinute(); !ok {
		return &ValidationError{Name: "start_minute", err: errors.New(`ent: missing required field "ModelPriceWindow.start_minute"`)}
	}
	if v, ok := _c.mutation.StartMinute(); ok {
		if err := modelpricewindow.StartMinuteValidator(v); err != nil {
			return &ValidationError{Name: "start_minute", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.start_minute": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EndMinute(); !ok {
		return &ValidationError{Name: "end_minute", err: errors.New(`ent: missing required field "ModelPriceWindow.end_minute"`)}
	}
	if v, ok := _c.mutation.EndMinute(); ok {
		if err := modelpricewindow.EndMinuteValidator(v); err != nil {
			return &ValidationError{Name: "end_minute", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.end_minute": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputPriceMicros(); !ok {
		return &ValidationError{Name: "input_price_micros", err: errors.New(`ent: missing required field "ModelPriceWindow.input_price_micros"`)}
	}
	if v, ok := _c.mutation.InputPriceMicros(); ok {
		if err := modelpricewindow.InputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "input_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.input_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OutputPriceMicros(); !ok {
		return &ValidationError{Name: "output_price_micros", err: errors.New(`ent: missing required field "ModelPriceWindow.output_price_micros"`)}
	}
	if v, ok := _c.mutation.OutputPriceMicros(); ok {
		if err := modelpricewindow.OutputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "output_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.output_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CacheReadPriceMicros(); !ok {
		return &ValidationError{Name: "cache_read_price_micros", err: errors.New(`ent: missing required field "ModelPriceWindow.cache_read_price_micros"`)}
	}
	if v, ok := _c.mutation.CacheReadPriceMicros(); ok {
		if err := modelpricewindow.CacheReadPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_read_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.cache_read_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CacheWritePriceMicros(); !ok {
		return &ValidationError{Name: "cache_write_price_micros", err: errors.New(`ent: missing required field "ModelPriceWindow.cache_write_price_micros"`)}
	}
	if v, ok := _c.mutation.CacheWritePriceMicros(); ok {
		if err := modelpricewindow.CacheWritePriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_write_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.cache_write_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CacheWrite1hPriceMicros(); !ok {
		return &ValidationError{Name: "cache_write_1h_price_micros", err: errors.New(`ent: missing required field "ModelPriceWindow.cache_write_1h_price_micros"`)}
	}
	if v, ok := _c.mutation.CacheWrite1hPriceMicros(); ok {
		if err := modelpricewindow.CacheWrite1hPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_write_1h_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.cache_write_1h_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestPriceMicros(); !ok {
		return &ValidationError{Name: "request_price_micros", err: errors.New(`ent: missing required field "ModelPriceWindow.request_price_micros"`)}
	}
	if v, ok := _c.mutation.RequestPriceMicros(); ok {
		if err := modelpricewindow.RequestPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "request_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelPriceWindow.request_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelPriceWindow.created_at"`)}
	}
	if len(_c.mutation.PricePlanIDs()) == 0 {
		return &ValidationError{Name: "price_plan", err: errors.New(`ent: missing required edge "ModelPriceWindow.price_plan"`)}
	}
	return nil
}

func (_c *ModelPriceWindowCreate) sqlSave(ctx context.Context) (*ModelPriceWindow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelPriceWindowCreate) createSpec() (*ModelPriceWindow, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelPriceWindow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelpricewindow.Table, sqlgraph.NewFieldSpec(modelpricewindow.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(modelpricewindow.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.WeekdayMask(); ok {
		_spec.SetField(modelpricewindow.FieldWeekdayMask, field.TypeInt, value)
		_node.WeekdayMask = value
	}
	if value, ok := _c.mutation.StartMinute(); ok {
		_spec.SetField(modelpricewindow.FieldStartMinute, field.TypeInt, value)
		_node.StartMinute = value
	}
	if value, ok := _c.mutation.EndMinute(); ok {
		_spec.SetField(modelpricewindow.FieldEndMinute, field.TypeInt, value)
		_node.EndMinute = value
	}
	if value, ok := _c.mutation.InputPriceMicros(); ok {
		_spec.SetField(modelpricewindow.FieldInputPriceMicros, field.TypeInt64, value)
		_node.InputPriceMicros = value
	}
	if value, ok := _c.mutation.OutputPriceMicros(); ok {
		_spec.SetField(modelpricewindow.FieldOutputPriceMicros, field.TypeInt64, value)
		_node.OutputPriceMicros = value
	}
	if value, ok := _c.mutation.CacheReadPriceMicros(); ok {
		_spec.SetField(modelpricewindow.FieldCacheReadPriceMicros, field.TypeInt64, value)
		_node.CacheReadPriceMicros = value
	}
	if value, ok := _c.mutation.CacheWritePriceMicros(); ok {
		_spec.SetField(modelpricewindow.FieldCacheWritePriceMicros, field.TypeInt64, value)
		_node.CacheWritePriceMicros = value
	}
	if value, ok := _c.mutation.CacheWrite1hPriceMicros(); ok {
		_spec.SetField(modelpricewindow.FieldCacheWrite1hPriceMicros, field.TypeInt64, value)
		_node.CacheWrite1hPriceMicros = value
	}
	if value, ok := _c.mutation.RequestPriceMicros(); ok {
		_spec.SetField(modelpricewindow.FieldRequestPriceMicros, field.TypeInt64, value)
		_node.RequestPriceMicros = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelpricewindow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PricePlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelpricewindow.PricePlanTable,
			Columns: []string{modelpricewindow.PricePlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpriceplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PricePlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ModelPriceWindowCreateBulk is the builder for creating many ModelPriceWindow entities in bulk.
type ModelPriceWindowCreateBulk struct {
	config
	err      error
	builders []*ModelPriceWindowCreate
}

// Save creates the ModelPriceWindow entities in the database.
func (_c *ModelPriceWindowCreateBulk) Save(ctx context.Context) ([]*ModelPriceWindow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelPriceWindow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelPriceWindowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelPriceWindowCreateBulk) SaveX(ctx context.Context) []*ModelPriceWindow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelPriceWindowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelPriceWindowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
