// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/novro-gateway/novro/ent/apiusage"
	"github.com/novro-gateway/novro/ent/modelroute"
	"github.com/novro-gateway/novro/ent/provider"
)

// ModelRouteCreate is the builder for creating a ModelRoute entity.
type ModelRouteCreate struct {
	config
	mutation *ModelRouteMutation
	hooks    []Hook
}

// SetProviderID sets the "provider_id" field.
func (_c *ModelRouteCreate) SetProviderID(v uuid.UUID) *ModelRouteCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetPublicName sets the "public_name" field.
func (_c *ModelRouteCreate) SetPublicName(v string) *ModelRouteCreate {
	_c.mutation.SetPublicName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ModelRouteCreate) SetDisplayName(v string) *ModelRouteCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetUpstreamName sets the "upstream_name" field.
func (_c *ModelRouteCreate) SetUpstreamName(v string) *ModelRouteCreate {
	_c.mutation.SetUpstreamName(v)
	return _c
}

// SetInputPriceMicros sets the "input_price_micros" field.
func (_c *ModelRouteCreate) SetInputPriceMicros(v int64) *ModelRouteCreate {
	_c.mutation.SetInputPriceMicros(v)
	return _c
}

// SetOutputPriceMicros sets the "output_price_micros" field.
func (_c *ModelRouteCreate) SetOutputPriceMicros(v int64) *ModelRouteCreate {
	_c.mutation.SetOutputPriceMicros(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelRouteCreate) SetStatus(v modelroute.Status) *ModelRouteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableStatus(v *modelroute.Status) *ModelRouteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelRouteCreate) SetCreatedAt(v time.Time) *ModelRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableCreatedAt(v *time.Time) *ModelRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelRouteCreate) SetUpdatedAt(v time.Time) *ModelRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableUpdatedAt(v *time.Time) *ModelRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelRouteCreate) SetID(v uuid.UUID) *ModelRouteCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ModelRouteCreate) SetNillableID(v *uuid.UUID) *ModelRouteCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProvider sets the "provider" edge to the Provider entity.
func (_c *ModelRouteCreate) SetProvider(v *Provider) *ModelRouteCreate {
	return _c.SetProviderID(v.ID)
}

// AddAPIUsageIDs adds the "api_usages" edge to the APIUsage entity by IDs.
func (_c *ModelRouteCreate) AddAPIUsageIDs(ids ...uuid.UUID) *ModelRouteCreate {
	_c.mutation.AddAPIUsageIDs(ids...)
	return _c
}

// AddAPIUsages adds the "api_usages" edges to the APIUsage entity.
func (_c *ModelRouteCreate) AddAPIUsages(v ...*APIUsage) *ModelRouteCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIUsageIDs(ids...)
}

// Mutation returns the ModelRouteMutation object of the builder.
func (_c *ModelRouteCreate) Mutation() *ModelRouteMutation {
	return _c.mutation
}

// Save creates the ModelRoute in the database.
func (_c *ModelRouteCreate) Save(ctx context.Context) (*ModelRoute, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelRouteCreate) SaveX(ctx context.Context) *ModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelRouteCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := modelroute.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelroute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelroute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := modelroute.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelRouteCreate) check() error {
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "ModelRoute.provider_id"`)}
	}
	if _, ok := _c.mutation.PublicName(); !ok {
		return &ValidationError{Name: "public_name", err: errors.New(`ent: missing required field "ModelRoute.public_name"`)}
	}
	if v, ok := _c.mutation.PublicName(); ok {
		if err := modelroute.PublicNameValidator(v); err != nil {
			return &ValidationError{Name: "public_name", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.public_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "ModelRoute.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := modelroute.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamName(); !ok {
		return &ValidationError{Name: "upstream_name", err: errors.New(`ent: missing required field "ModelRoute.upstream_name"`)}
	}
	if v, ok := _c.mutation.UpstreamName(); ok {
		if err := modelroute.UpstreamNameValidator(v); err != nil {
			return &ValidationError{Name: "upstream_name", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.upstream_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InputPriceMicros(); !ok {
		return &ValidationError{Name: "input_price_micros", err: errors.New(`ent: missing required field "ModelRoute.input_price_micros"`)}
	}
	if v, ok := _c.mutation.InputPriceMicros(); ok {
		if err := modelroute.InputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "input_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.input_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OutputPriceMicros(); !ok {
		return &ValidationError{Name: "output_price_micros", err: errors.New(`ent: missing required field "ModelRoute.output_price_micros"`)}
	}
	if v, ok := _c.mutation.OutputPriceMicros(); ok {
		if err := modelroute.OutputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "output_price_micros", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.output_price_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ModelRoute.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := modelroute.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelRoute.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelRoute.updated_at"`)}
	}
	if len(_c.mutation.ProviderIDs()) == 0 {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required edge "ModelRoute.provider"`)}
	}
	return nil
}

func (_c *ModelRouteCreate) sqlSave(ctx context.Context) (*ModelRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelRouteCreate) createSpec() (*ModelRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelroute.Table, sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PublicName(); ok {
		_spec.SetField(modelroute.FieldPublicName, field.TypeString, value)
		_node.PublicName = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(modelroute.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.UpstreamName(); ok {
		_spec.SetField(modelroute.FieldUpstreamName, field.TypeString, value)
		_node.UpstreamName = value
	}
	if value, ok := _c.mutation.InputPriceMicros(); ok {
		_spec.SetField(modelroute.FieldInputPriceMicros, field.TypeInt64, value)
		_node.InputPriceMicros = value
	}
	if value, ok := _c.mutation.OutputPriceMicros(); ok {
		_spec.SetField(modelroute.FieldOutputPriceMicros, field.TypeInt64, value)
		_node.OutputPriceMicros = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(modelroute.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelroute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelroute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   modelroute.ProviderTable,
			Columns: []string{modelroute.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(provider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProviderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIUsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelroute.APIUsagesTable,
			Columns: []string{modelroute.APIUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ModelRouteCreateBulk is the builder for creating many ModelRoute entities in bulk.
type ModelRouteCreateBulk struct {
	config
	err      error
	builders []*ModelRouteCreate
}

// Save creates the ModelRoute entities in the database.
func (_c *ModelRouteCreateBulk) Save(ctx context.Context) ([]*ModelRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelRouteCreateBulk) SaveX(ctx context.Context) []*ModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
