// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/novro-gateway/novro/ent/paymentconfig"
)

// PaymentConfig is the model entity for the PaymentConfig schema.
type PaymentConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// APIURL holds the value of the "api_url" field.
	APIURL string `json:"api_url,omitempty"`
	// MerchantID holds the value of the "merchant_id" field.
	MerchantID string `json:"merchant_id,omitempty"`
	// EncryptedMerchantKey holds the value of the "encrypted_merchant_key" field.
	EncryptedMerchantKey string `json:"-"`
	// SiteName holds the value of the "site_name" field.
	SiteName string `json:"site_name,omitempty"`
	// Channels holds the value of the "channels" field.
	Channels string `json:"channels,omitempty"`
	// MethodsJSON holds the value of the "methods_json" field.
	MethodsJSON string `json:"methods_json,omitempty"`
	// MinTopUpMicros holds the value of the "min_top_up_micros" field.
	MinTopUpMicros int64 `json:"min_top_up_micros,omitempty"`
	// MaxTopUpMicros holds the value of the "max_top_up_micros" field.
	MaxTopUpMicros int64 `json:"max_top_up_micros,omitempty"`
	// PresetAmountsJSON holds the value of the "preset_amounts_json" field.
	PresetAmountsJSON string `json:"preset_amounts_json,omitempty"`
	// BonusTiersJSON holds the value of the "bonus_tiers_json" field.
	BonusTiersJSON string `json:"bonus_tiers_json,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentconfig.FieldEnabled:
			values[i] = new(sql.NullBool)
		case paymentconfig.FieldMinTopUpMicros, paymentconfig.FieldMaxTopUpMicros:
			values[i] = new(sql.NullInt64)
		case paymentconfig.FieldID, paymentconfig.FieldAPIURL, paymentconfig.FieldMerchantID, paymentconfig.FieldEncryptedMerchantKey, paymentconfig.FieldSiteName, paymentconfig.FieldChannels, paymentconfig.FieldMethodsJSON, paymentconfig.FieldPresetAmountsJSON, paymentconfig.FieldBonusTiersJSON:
			values[i] = new(sql.NullString)
		case paymentconfig.FieldCreatedAt, paymentconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentConfig fields.
func (_m *PaymentConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case paymentconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case paymentconfig.FieldAPIURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_url", values[i])
			} else if value.Valid {
				_m.APIURL = value.String
			}
		case paymentconfig.FieldMerchantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field merchant_id", values[i])
			} else if value.Valid {
				_m.MerchantID = value.String
			}
		case paymentconfig.FieldEncryptedMerchantKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_merchant_key", values[i])
			} else if value.Valid {
				_m.EncryptedMerchantKey = value.String
			}
		case paymentconfig.FieldSiteName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_name", values[i])
			} else if value.Valid {
				_m.SiteName = value.String
			}
		case paymentconfig.FieldChannels:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channels", values[i])
			} else if value.Valid {
				_m.Channels = value.String
			}
		case paymentconfig.FieldMethodsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field methods_json", values[i])
			} else if value.Valid {
				_m.MethodsJSON = value.String
			}
		case paymentconfig.FieldMinTopUpMicros:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_top_up_micros", values[i])
			} else if value.Valid {
				_m.MinTopUpMicros = value.Int64
			}
		case paymentconfig.FieldMaxTopUpMicros:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_top_up_micros", values[i])
			} else if value.Valid {
				_m.MaxTopUpMicros = value.Int64
			}
		case paymentconfig.FieldPresetAmountsJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preset_amounts_json", values[i])
			} else if value.Valid {
				_m.PresetAmountsJSON = value.String
			}
		case paymentconfig.FieldBonusTiersJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_tiers_json", values[i])
			} else if value.Valid {
				_m.BonusTiersJSON = value.String
			}
		case paymentconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentConfig.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PaymentConfig.
// Note that you need to call PaymentConfig.Unwrap() before calling this method if this PaymentConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentConfig) Update() *PaymentConfigUpdateOne {
	return NewPaymentConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentConfig) Unwrap() *PaymentConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentConfig) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("api_url=")
	builder.WriteString(_m.APIURL)
	builder.WriteString(", ")
	builder.WriteString("merchant_id=")
	builder.WriteString(_m.MerchantID)
	builder.WriteString(", ")
	builder.WriteString("encrypted_merchant_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("site_name=")
	builder.WriteString(_m.SiteName)
	builder.WriteString(", ")
	builder.WriteString("channels=")
	builder.WriteString(_m.Channels)
	builder.WriteString(", ")
	builder.WriteString("methods_json=")
	builder.WriteString(_m.MethodsJSON)
	builder.WriteString(", ")
	builder.WriteString("min_top_up_micros=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinTopUpMicros))
	builder.WriteString(", ")
	builder.WriteString("max_top_up_micros=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxTopUpMicros))
	builder.WriteString(", ")
	builder.WriteString("preset_amounts_json=")
	builder.WriteString(_m.PresetAmountsJSON)
	builder.WriteString(", ")
	builder.WriteString("bonus_tiers_json=")
	builder.WriteString(_m.BonusTiersJSON)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentConfigs is a parsable slice of PaymentConfig.
type PaymentConfigs []*PaymentConfig
