// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/novro-gateway/novro/ent/modelroute"
	"github.com/novro-gateway/novro/ent/predicate"
	"github.com/novro-gateway/novro/ent/provider"
)

// ProviderUpdate is the builder for updating Provider entities.
type ProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderMutation
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdate) Where(ps ...predicate.Provider) *ProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ProviderUpdate) SetDisplayName(v string) *ProviderUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableDisplayName(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProviderUpdate) SetProtocol(v provider.Protocol) *ProviderUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableProtocol(v *provider.Protocol) *ProviderUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ProviderUpdate) SetBaseURL(v string) *ProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableBaseURL(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetEncryptedAPIKey sets the "encrypted_api_key" field.
func (_u *ProviderUpdate) SetEncryptedAPIKey(v string) *ProviderUpdate {
	_u.mutation.SetEncryptedAPIKey(v)
	return _u
}

// SetNillableEncryptedAPIKey sets the "encrypted_api_key" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableEncryptedAPIKey(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetEncryptedAPIKey(*v)
	}
	return _u
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (_u *ProviderUpdate) SetAPIKeyHint(v string) *ProviderUpdate {
	_u.mutation.SetAPIKeyHint(v)
	return _u
}

// SetNillableAPIKeyHint sets the "api_key_hint" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableAPIKeyHint(v *string) *ProviderUpdate {
	if v != nil {
		_u.SetAPIKeyHint(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderUpdate) SetStatus(v provider.Status) *ProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableStatus(v *provider.Status) *ProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderUpdate) SetUpdatedAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProviderUpdate) SetDeletedAt(v time.Time) *ProviderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProviderUpdate) SetNillableDeletedAt(v *time.Time) *ProviderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProviderUpdate) ClearDeletedAt() *ProviderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddModelRouteIDs adds the "model_routes" edge to the ModelRoute entity by IDs.
func (_u *ProviderUpdate) AddModelRouteIDs(ids ...uuid.UUID) *ProviderUpdate {
	_u.mutation.AddModelRouteIDs(ids...)
	return _u
}

// AddModelRoutes adds the "model_routes" edges to the ModelRoute entity.
func (_u *ProviderUpdate) AddModelRoutes(v ...*ModelRoute) *ProviderUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelRouteIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdate) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearModelRoutes clears all "model_routes" edges to the ModelRoute entity.
func (_u *ProviderUpdate) ClearModelRoutes() *ProviderUpdate {
	_u.mutation.ClearModelRoutes()
	return _u
}

// RemoveModelRouteIDs removes the "model_routes" edge to ModelRoute entities by IDs.
func (_u *ProviderUpdate) RemoveModelRouteIDs(ids ...uuid.UUID) *ProviderUpdate {
	_u.mutation.RemoveModelRouteIDs(ids...)
	return _u
}

// RemoveModelRoutes removes "model_routes" edges to ModelRoute entities.
func (_u *ProviderUpdate) RemoveModelRoutes(v ...*ModelRoute) *ProviderUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelRouteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := provider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdate) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := provider.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Provider.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := provider.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Provider.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := provider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Provider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedAPIKey(); ok {
		if err := provider.EncryptedAPIKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_api_key", err: fmt.Errorf(`ent: validator failed for field "Provider.encrypted_api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyHint(); ok {
		if err := provider.APIKeyHintValidator(v); err != nil {
			return &ValidationError{Name: "api_key_hint", err: fmt.Errorf(`ent: validator failed for field "Provider.api_key_hint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := provider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Provider.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(provider.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(provider.FieldProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(provider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedAPIKey(); ok {
		_spec.SetField(provider.FieldEncryptedAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyHint(); ok {
		_spec.SetField(provider.FieldAPIKeyHint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(provider.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(provider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(provider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(provider.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ModelRoutesTable,
			Columns: []string{provider.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelRoutesIDs(); len(nodes) > 0 && !_u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ModelRoutesTable,
			Columns: []string{provider.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelRoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ModelRoutesTable,
			Columns: []string{provider.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderUpdateOne is the builder for updating a single Provider entity.
type ProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderMutation
}

// SetDisplayName sets the "display_name" field.
func (_u *ProviderUpdateOne) SetDisplayName(v string) *ProviderUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableDisplayName(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProviderUpdateOne) SetProtocol(v provider.Protocol) *ProviderUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableProtocol(v *provider.Protocol) *ProviderUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *ProviderUpdateOne) SetBaseURL(v string) *ProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableBaseURL(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetEncryptedAPIKey sets the "encrypted_api_key" field.
func (_u *ProviderUpdateOne) SetEncryptedAPIKey(v string) *ProviderUpdateOne {
	_u.mutation.SetEncryptedAPIKey(v)
	return _u
}

// SetNillableEncryptedAPIKey sets the "encrypted_api_key" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableEncryptedAPIKey(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetEncryptedAPIKey(*v)
	}
	return _u
}

// SetAPIKeyHint sets the "api_key_hint" field.
func (_u *ProviderUpdateOne) SetAPIKeyHint(v string) *ProviderUpdateOne {
	_u.mutation.SetAPIKeyHint(v)
	return _u
}

// SetNillableAPIKeyHint sets the "api_key_hint" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableAPIKeyHint(v *string) *ProviderUpdateOne {
	if v != nil {
		_u.SetAPIKeyHint(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderUpdateOne) SetStatus(v provider.Status) *ProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableStatus(v *provider.Status) *ProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProviderUpdateOne) SetUpdatedAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProviderUpdateOne) SetDeletedAt(v time.Time) *ProviderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProviderUpdateOne) SetNillableDeletedAt(v *time.Time) *ProviderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProviderUpdateOne) ClearDeletedAt() *ProviderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddModelRouteIDs adds the "model_routes" edge to the ModelRoute entity by IDs.
func (_u *ProviderUpdateOne) AddModelRouteIDs(ids ...uuid.UUID) *ProviderUpdateOne {
	_u.mutation.AddModelRouteIDs(ids...)
	return _u
}

// AddModelRoutes adds the "model_routes" edges to the ModelRoute entity.
func (_u *ProviderUpdateOne) AddModelRoutes(v ...*ModelRoute) *ProviderUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelRouteIDs(ids...)
}

// Mutation returns the ProviderMutation object of the builder.
func (_u *ProviderUpdateOne) Mutation() *ProviderMutation {
	return _u.mutation
}

// ClearModelRoutes clears all "model_routes" edges to the ModelRoute entity.
func (_u *ProviderUpdateOne) ClearModelRoutes() *ProviderUpdateOne {
	_u.mutation.ClearModelRoutes()
	return _u
}

// RemoveModelRouteIDs removes the "model_routes" edge to ModelRoute entities by IDs.
func (_u *ProviderUpdateOne) RemoveModelRouteIDs(ids ...uuid.UUID) *ProviderUpdateOne {
	_u.mutation.RemoveModelRouteIDs(ids...)
	return _u
}

// RemoveModelRoutes removes "model_routes" edges to ModelRoute entities.
func (_u *ProviderUpdateOne) RemoveModelRoutes(v ...*ModelRoute) *ProviderUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelRouteIDs(ids...)
}

// Where appends a list predicates to the ProviderUpdate builder.
func (_u *ProviderUpdateOne) Where(ps ...predicate.Provider) *ProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderUpdateOne) Select(field string, fields ...string) *ProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Provider entity.
func (_u *ProviderUpdateOne) Save(ctx context.Context) (*Provider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderUpdateOne) SaveX(ctx context.Context) *Provider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := provider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := provider.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Provider.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := provider.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Provider.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := provider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Provider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedAPIKey(); ok {
		if err := provider.EncryptedAPIKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_api_key", err: fmt.Errorf(`ent: validator failed for field "Provider.encrypted_api_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyHint(); ok {
		if err := provider.APIKeyHintValidator(v); err != nil {
			return &ValidationError{Name: "api_key_hint", err: fmt.Errorf(`ent: validator failed for field "Provider.api_key_hint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := provider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Provider.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderUpdateOne) sqlSave(ctx context.Context) (_node *Provider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Provider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provider.FieldID)
		for _, f := range fields {
			if !provider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != provider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(provider.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(provider.FieldProtocol, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(provider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.EncryptedAPIKey(); ok {
		_spec.SetField(provider.FieldEncryptedAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyHint(); ok {
		_spec.SetField(provider.FieldAPIKeyHint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(provider.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(provider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(provider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(provider.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ModelRoutesTable,
			Columns: []string{provider.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelRoutesIDs(); len(nodes) > 0 && !_u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ModelRoutesTable,
			Columns: []string{provider.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelRoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   provider.ModelRoutesTable,
			Columns: []string{provider.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Provider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
