// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/novro-gateway/novro/ent/topuporder"
	"github.com/novro-gateway/novro/ent/user"
)

// TopUpOrderCreate is the builder for creating a TopUpOrder entity.
type TopUpOrderCreate struct {
	config
	mutation *TopUpOrderMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *TopUpOrderCreate) SetUserID(v uuid.UUID) *TopUpOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_c *TopUpOrderCreate) SetOutTradeNo(v string) *TopUpOrderCreate {
	_c.mutation.SetOutTradeNo(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *TopUpOrderCreate) SetProvider(v topuporder.Provider) *TopUpOrderCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *TopUpOrderCreate) SetNillableProvider(v *topuporder.Provider) *TopUpOrderCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetChannel sets the "channel" field.
func (_c *TopUpOrderCreate) SetChannel(v string) *TopUpOrderCreate {
	_c.mutation.SetChannel(v)
	return _c
}

// SetAmountMicros sets the "amount_micros" field.
func (_c *TopUpOrderCreate) SetAmountMicros(v int64) *TopUpOrderCreate {
	_c.mutation.SetAmountMicros(v)
	return _c
}

// SetCreditedMicros sets the "credited_micros" field.
func (_c *TopUpOrderCreate) SetCreditedMicros(v int64) *TopUpOrderCreate {
	_c.mutation.SetCreditedMicros(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TopUpOrderCreate) SetStatus(v topuporder.Status) *TopUpOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TopUpOrderCreate) SetNillableStatus(v *topuporder.Status) *TopUpOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProviderTradeNo sets the "provider_trade_no" field.
func (_c *TopUpOrderCreate) SetProviderTradeNo(v string) *TopUpOrderCreate {
	_c.mutation.SetProviderTradeNo(v)
	return _c
}

// SetNillableProviderTradeNo sets the "provider_trade_no" field if the given value is not nil.
func (_c *TopUpOrderCreate) SetNillableProviderTradeNo(v *string) *TopUpOrderCreate {
	if v != nil {
		_c.SetProviderTradeNo(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *TopUpOrderCreate) SetPaidAt(v time.Time) *TopUpOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *TopUpOrderCreate) SetNillablePaidAt(v *time.Time) *TopUpOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TopUpOrderCreate) SetCreatedAt(v time.Time) *TopUpOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TopUpOrderCreate) SetNillableCreatedAt(v *time.Time) *TopUpOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TopUpOrderCreate) SetUpdatedAt(v time.Time) *TopUpOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TopUpOrderCreate) SetNillableUpdatedAt(v *time.Time) *TopUpOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TopUpOrderCreate) SetID(v uuid.UUID) *TopUpOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TopUpOrderCreate) SetNillableID(v *uuid.UUID) *TopUpOrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TopUpOrderCreate) SetUser(v *User) *TopUpOrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the TopUpOrderMutation object of the builder.
func (_c *TopUpOrderCreate) Mutation() *TopUpOrderMutation {
	return _c.mutation
}

// Save creates the TopUpOrder in the database.
func (_c *TopUpOrderCreate) Save(ctx context.Context) (*TopUpOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TopUpOrderCreate) SaveX(ctx context.Context) *TopUpOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TopUpOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TopUpOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TopUpOrderCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := topuporder.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := topuporder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := topuporder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := topuporder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := topuporder.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TopUpOrderCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TopUpOrder.user_id"`)}
	}
	if _, ok := _c.mutation.OutTradeNo(); !ok {
		return &ValidationError{Name: "out_trade_no", err: errors.New(`ent: missing required field "TopUpOrder.out_trade_no"`)}
	}
	if v, ok := _c.mutation.OutTradeNo(); ok {
		if err := topuporder.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "TopUpOrder.out_trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "TopUpOrder.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := topuporder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "TopUpOrder.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Channel(); !ok {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required field "TopUpOrder.channel"`)}
	}
	if v, ok := _c.mutation.Channel(); ok {
		if err := topuporder.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "TopUpOrder.channel": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountMicros(); !ok {
		return &ValidationError{Name: "amount_micros", err: errors.New(`ent: missing required field "TopUpOrder.amount_micros"`)}
	}
	if v, ok := _c.mutation.AmountMicros(); ok {
		if err := topuporder.AmountMicrosValidator(v); err != nil {
			return &ValidationError{Name: "amount_micros", err: fmt.Errorf(`ent: validator failed for field "TopUpOrder.amount_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreditedMicros(); !ok {
		return &ValidationError{Name: "credited_micros", err: errors.New(`ent: missing required field "TopUpOrder.credited_micros"`)}
	}
	if v, ok := _c.mutation.CreditedMicros(); ok {
		if err := topuporder.CreditedMicrosValidator(v); err != nil {
			return &ValidationError{Name: "credited_micros", err: fmt.Errorf(`ent: validator failed for field "TopUpOrder.credited_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TopUpOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := topuporder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TopUpOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderTradeNo(); ok {
		if err := topuporder.ProviderTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_trade_no", err: fmt.Errorf(`ent: validator failed for field "TopUpOrder.provider_trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TopUpOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TopUpOrder.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TopUpOrder.user"`)}
	}
	return nil
}

func (_c *TopUpOrderCreate) sqlSave(ctx context.Context) (*TopUpOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TopUpOrderCreate) createSpec() (*TopUpOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &TopUpOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(topuporder.Table, sqlgraph.NewFieldSpec(topuporder.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OutTradeNo(); ok {
		_spec.SetField(topuporder.FieldOutTradeNo, field.TypeString, value)
		_node.OutTradeNo = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(topuporder.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Channel(); ok {
		_spec.SetField(topuporder.FieldChannel, field.TypeString, value)
		_node.Channel = value
	}
	if value, ok := _c.mutation.AmountMicros(); ok {
		_spec.SetField(topuporder.FieldAmountMicros, field.TypeInt64, value)
		_node.AmountMicros = value
	}
	if value, ok := _c.mutation.CreditedMicros(); ok {
		_spec.SetField(topuporder.FieldCreditedMicros, field.TypeInt64, value)
		_node.CreditedMicros = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(topuporder.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProviderTradeNo(); ok {
		_spec.SetField(topuporder.FieldProviderTradeNo, field.TypeString, value)
		_node.ProviderTradeNo = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(topuporder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(topuporder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(topuporder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   topuporder.UserTable,
			Columns: []string{topuporder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TopUpOrderCreateBulk is the builder for creating many TopUpOrder entities in bulk.
type TopUpOrderCreateBulk struct {
	config
	err      error
	builders []*TopUpOrderCreate
}

// Save creates the TopUpOrder entities in the database.
func (_c *TopUpOrderCreateBulk) Save(ctx context.Context) ([]*TopUpOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TopUpOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TopUpOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TopUpOrderCreateBulk) SaveX(ctx context.Context) []*TopUpOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TopUpOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TopUpOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
