// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/novro-gateway/novro/ent/apiusage"
	"github.com/novro-gateway/novro/ent/modelpriceplan"
	"github.com/novro-gateway/novro/ent/modelroute"
	"github.com/novro-gateway/novro/ent/predicate"
	"github.com/novro-gateway/novro/ent/upstreammodel"
)

// UpstreamModelUpdate is the builder for updating UpstreamModel entities.
type UpstreamModelUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamModelMutation
}

// Where appends a list predicates to the UpstreamModelUpdate builder.
func (_u *UpstreamModelUpdate) Where(ps ...predicate.UpstreamModel) *UpstreamModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderName sets the "provider_name" field.
func (_u *UpstreamModelUpdate) SetProviderName(v string) *UpstreamModelUpdate {
	_u.mutation.SetProviderName(v)
	return _u
}

// SetNillableProviderName sets the "provider_name" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableProviderName(v *string) *UpstreamModelUpdate {
	if v != nil {
		_u.SetProviderName(*v)
	}
	return _u
}

// SetUpstreamName sets the "upstream_name" field.
func (_u *UpstreamModelUpdate) SetUpstreamName(v string) *UpstreamModelUpdate {
	_u.mutation.SetUpstreamName(v)
	return _u
}

// SetNillableUpstreamName sets the "upstream_name" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableUpstreamName(v *string) *UpstreamModelUpdate {
	if v != nil {
		_u.SetUpstreamName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *UpstreamModelUpdate) SetDisplayName(v string) *UpstreamModelUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableDisplayName(v *string) *UpstreamModelUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetInputPriceMicros sets the "input_price_micros" field.
func (_u *UpstreamModelUpdate) SetInputPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.ResetInputPriceMicros()
	_u.mutation.SetInputPriceMicros(v)
	return _u
}

// SetNillableInputPriceMicros sets the "input_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableInputPriceMicros(v *int64) *UpstreamModelUpdate {
	if v != nil {
		_u.SetInputPriceMicros(*v)
	}
	return _u
}

// AddInputPriceMicros adds value to the "input_price_micros" field.
func (_u *UpstreamModelUpdate) AddInputPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.AddInputPriceMicros(v)
	return _u
}

// SetOutputPriceMicros sets the "output_price_micros" field.
func (_u *UpstreamModelUpdate) SetOutputPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.ResetOutputPriceMicros()
	_u.mutation.SetOutputPriceMicros(v)
	return _u
}

// SetNillableOutputPriceMicros sets the "output_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableOutputPriceMicros(v *int64) *UpstreamModelUpdate {
	if v != nil {
		_u.SetOutputPriceMicros(*v)
	}
	return _u
}

// AddOutputPriceMicros adds value to the "output_price_micros" field.
func (_u *UpstreamModelUpdate) AddOutputPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.AddOutputPriceMicros(v)
	return _u
}

// SetCacheReadPriceMicros sets the "cache_read_price_micros" field.
func (_u *UpstreamModelUpdate) SetCacheReadPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.ResetCacheReadPriceMicros()
	_u.mutation.SetCacheReadPriceMicros(v)
	return _u
}

// SetNillableCacheReadPriceMicros sets the "cache_read_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableCacheReadPriceMicros(v *int64) *UpstreamModelUpdate {
	if v != nil {
		_u.SetCacheReadPriceMicros(*v)
	}
	return _u
}

// AddCacheReadPriceMicros adds value to the "cache_read_price_micros" field.
func (_u *UpstreamModelUpdate) AddCacheReadPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.AddCacheReadPriceMicros(v)
	return _u
}

// SetCacheWritePriceMicros sets the "cache_write_price_micros" field.
func (_u *UpstreamModelUpdate) SetCacheWritePriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.ResetCacheWritePriceMicros()
	_u.mutation.SetCacheWritePriceMicros(v)
	return _u
}

// SetNillableCacheWritePriceMicros sets the "cache_write_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableCacheWritePriceMicros(v *int64) *UpstreamModelUpdate {
	if v != nil {
		_u.SetCacheWritePriceMicros(*v)
	}
	return _u
}

// AddCacheWritePriceMicros adds value to the "cache_write_price_micros" field.
func (_u *UpstreamModelUpdate) AddCacheWritePriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.AddCacheWritePriceMicros(v)
	return _u
}

// SetCacheWrite1hPriceMicros sets the "cache_write_1h_price_micros" field.
func (_u *UpstreamModelUpdate) SetCacheWrite1hPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.ResetCacheWrite1hPriceMicros()
	_u.mutation.SetCacheWrite1hPriceMicros(v)
	return _u
}

// SetNillableCacheWrite1hPriceMicros sets the "cache_write_1h_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableCacheWrite1hPriceMicros(v *int64) *UpstreamModelUpdate {
	if v != nil {
		_u.SetCacheWrite1hPriceMicros(*v)
	}
	return _u
}

// AddCacheWrite1hPriceMicros adds value to the "cache_write_1h_price_micros" field.
func (_u *UpstreamModelUpdate) AddCacheWrite1hPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.AddCacheWrite1hPriceMicros(v)
	return _u
}

// SetRequestPriceMicros sets the "request_price_micros" field.
func (_u *UpstreamModelUpdate) SetRequestPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.ResetRequestPriceMicros()
	_u.mutation.SetRequestPriceMicros(v)
	return _u
}

// SetNillableRequestPriceMicros sets the "request_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableRequestPriceMicros(v *int64) *UpstreamModelUpdate {
	if v != nil {
		_u.SetRequestPriceMicros(*v)
	}
	return _u
}

// AddRequestPriceMicros adds value to the "request_price_micros" field.
func (_u *UpstreamModelUpdate) AddRequestPriceMicros(v int64) *UpstreamModelUpdate {
	_u.mutation.AddRequestPriceMicros(v)
	return _u
}

// SetPricingConfigured sets the "pricing_configured" field.
func (_u *UpstreamModelUpdate) SetPricingConfigured(v bool) *UpstreamModelUpdate {
	_u.mutation.SetPricingConfigured(v)
	return _u
}

// SetNillablePricingConfigured sets the "pricing_configured" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillablePricingConfigured(v *bool) *UpstreamModelUpdate {
	if v != nil {
		_u.SetPricingConfigured(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamModelUpdate) SetStatus(v upstreammodel.Status) *UpstreamModelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableStatus(v *upstreammodel.Status) *UpstreamModelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamModelUpdate) SetUpdatedAt(v time.Time) *UpstreamModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamModelUpdate) SetDeletedAt(v time.Time) *UpstreamModelUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamModelUpdate) SetNillableDeletedAt(v *time.Time) *UpstreamModelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamModelUpdate) ClearDeletedAt() *UpstreamModelUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddModelRouteIDs adds the "model_routes" edge to the ModelRoute entity by IDs.
func (_u *UpstreamModelUpdate) AddModelRouteIDs(ids ...uuid.UUID) *UpstreamModelUpdate {
	_u.mutation.AddModelRouteIDs(ids...)
	return _u
}

// AddModelRoutes adds the "model_routes" edges to the ModelRoute entity.
func (_u *UpstreamModelUpdate) AddModelRoutes(v ...*ModelRoute) *UpstreamModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelRouteIDs(ids...)
}

// AddAPIUsageIDs adds the "api_usages" edge to the APIUsage entity by IDs.
func (_u *UpstreamModelUpdate) AddAPIUsageIDs(ids ...uuid.UUID) *UpstreamModelUpdate {
	_u.mutation.AddAPIUsageIDs(ids...)
	return _u
}

// AddAPIUsages adds the "api_usages" edges to the APIUsage entity.
func (_u *UpstreamModelUpdate) AddAPIUsages(v ...*APIUsage) *UpstreamModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIUsageIDs(ids...)
}

// AddPricePlanIDs adds the "price_plans" edge to the ModelPricePlan entity by IDs.
func (_u *UpstreamModelUpdate) AddPricePlanIDs(ids ...uuid.UUID) *UpstreamModelUpdate {
	_u.mutation.AddPricePlanIDs(ids...)
	return _u
}

// AddPricePlans adds the "price_plans" edges to the ModelPricePlan entity.
func (_u *UpstreamModelUpdate) AddPricePlans(v ...*ModelPricePlan) *UpstreamModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPricePlanIDs(ids...)
}

// Mutation returns the UpstreamModelMutation object of the builder.
func (_u *UpstreamModelUpdate) Mutation() *UpstreamModelMutation {
	return _u.mutation
}

// ClearModelRoutes clears all "model_routes" edges to the ModelRoute entity.
func (_u *UpstreamModelUpdate) ClearModelRoutes() *UpstreamModelUpdate {
	_u.mutation.ClearModelRoutes()
	return _u
}

// RemoveModelRouteIDs removes the "model_routes" edge to ModelRoute entities by IDs.
func (_u *UpstreamModelUpdate) RemoveModelRouteIDs(ids ...uuid.UUID) *UpstreamModelUpdate {
	_u.mutation.RemoveModelRouteIDs(ids...)
	return _u
}

// RemoveModelRoutes removes "model_routes" edges to ModelRoute entities.
func (_u *UpstreamModelUpdate) RemoveModelRoutes(v ...*ModelRoute) *UpstreamModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelRouteIDs(ids...)
}

// ClearAPIUsages clears all "api_usages" edges to the APIUsage entity.
func (_u *UpstreamModelUpdate) ClearAPIUsages() *UpstreamModelUpdate {
	_u.mutation.ClearAPIUsages()
	return _u
}

// RemoveAPIUsageIDs removes the "api_usages" edge to APIUsage entities by IDs.
func (_u *UpstreamModelUpdate) RemoveAPIUsageIDs(ids ...uuid.UUID) *UpstreamModelUpdate {
	_u.mutation.RemoveAPIUsageIDs(ids...)
	return _u
}

// RemoveAPIUsages removes "api_usages" edges to APIUsage entities.
func (_u *UpstreamModelUpdate) RemoveAPIUsages(v ...*APIUsage) *UpstreamModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIUsageIDs(ids...)
}

// ClearPricePlans clears all "price_plans" edges to the ModelPricePlan entity.
func (_u *UpstreamModelUpdate) ClearPricePlans() *UpstreamModelUpdate {
	_u.mutation.ClearPricePlans()
	return _u
}

// RemovePricePlanIDs removes the "price_plans" edge to ModelPricePlan entities by IDs.
func (_u *UpstreamModelUpdate) RemovePricePlanIDs(ids ...uuid.UUID) *UpstreamModelUpdate {
	_u.mutation.RemovePricePlanIDs(ids...)
	return _u
}

// RemovePricePlans removes "price_plans" edges to ModelPricePlan entities.
func (_u *UpstreamModelUpdate) RemovePricePlans(v ...*ModelPricePlan) *UpstreamModelUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePricePlanIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreammodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamModelUpdate) check() error {
	if v, ok := _u.mutation.ProviderName(); ok {
		if err := upstreammodel.ProviderNameValidator(v); err != nil {
			return &ValidationError{Name: "provider_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.provider_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamName(); ok {
		if err := upstreammodel.UpstreamNameValidator(v); err != nil {
			return &ValidationError{Name: "upstream_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.upstream_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := upstreammodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputPriceMicros(); ok {
		if err := upstreammodel.InputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "input_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.input_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputPriceMicros(); ok {
		if err := upstreammodel.OutputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "output_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.output_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheReadPriceMicros(); ok {
		if err := upstreammodel.CacheReadPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_read_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.cache_read_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheWritePriceMicros(); ok {
		if err := upstreammodel.CacheWritePriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_write_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.cache_write_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheWrite1hPriceMicros(); ok {
		if err := upstreammodel.CacheWrite1hPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_write_1h_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.cache_write_1h_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPriceMicros(); ok {
		if err := upstreammodel.RequestPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "request_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.request_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreammodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreammodel.Table, upstreammodel.Columns, sqlgraph.NewFieldSpec(upstreammodel.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderName(); ok {
		_spec.SetField(upstreammodel.FieldProviderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamName(); ok {
		_spec.SetField(upstreammodel.FieldUpstreamName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(upstreammodel.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldInputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldInputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldOutputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldOutputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldCacheReadPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldCacheReadPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWritePriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldCacheWritePriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldCacheWritePriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWrite1hPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldCacheWrite1hPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldCacheWrite1hPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldRequestPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldRequestPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PricingConfigured(); ok {
		_spec.SetField(upstreammodel.FieldPricingConfigured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreammodel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreammodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreammodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreammodel.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.ModelRoutesTable,
			Columns: []string{upstreammodel.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelRoutesIDs(); len(nodes) > 0 && !_u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.ModelRoutesTable,
			Columns: []string{upstreammodel.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelRoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.ModelRoutesTable,
			Columns: []string{upstreammodel.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIUsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.APIUsagesTable,
			Columns: []string{upstreammodel.APIUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIUsagesIDs(); len(nodes) > 0 && !_u.mutation.APIUsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.APIUsagesTable,
			Columns: []string{upstreammodel.APIUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIUsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.APIUsagesTable,
			Columns: []string{upstreammodel.APIUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PricePlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.PricePlansTable,
			Columns: []string{upstreammodel.PricePlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpriceplan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricePlansIDs(); len(nodes) > 0 && !_u.mutation.PricePlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.PricePlansTable,
			Columns: []string{upstreammodel.PricePlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpriceplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricePlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.PricePlansTable,
			Columns: []string{upstreammodel.PricePlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpriceplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreammodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamModelUpdateOne is the builder for updating a single UpstreamModel entity.
type UpstreamModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamModelMutation
}

// SetProviderName sets the "provider_name" field.
func (_u *UpstreamModelUpdateOne) SetProviderName(v string) *UpstreamModelUpdateOne {
	_u.mutation.SetProviderName(v)
	return _u
}

// SetNillableProviderName sets the "provider_name" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableProviderName(v *string) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetProviderName(*v)
	}
	return _u
}

// SetUpstreamName sets the "upstream_name" field.
func (_u *UpstreamModelUpdateOne) SetUpstreamName(v string) *UpstreamModelUpdateOne {
	_u.mutation.SetUpstreamName(v)
	return _u
}

// SetNillableUpstreamName sets the "upstream_name" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableUpstreamName(v *string) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetUpstreamName(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *UpstreamModelUpdateOne) SetDisplayName(v string) *UpstreamModelUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableDisplayName(v *string) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetInputPriceMicros sets the "input_price_micros" field.
func (_u *UpstreamModelUpdateOne) SetInputPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.ResetInputPriceMicros()
	_u.mutation.SetInputPriceMicros(v)
	return _u
}

// SetNillableInputPriceMicros sets the "input_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableInputPriceMicros(v *int64) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetInputPriceMicros(*v)
	}
	return _u
}

// AddInputPriceMicros adds value to the "input_price_micros" field.
func (_u *UpstreamModelUpdateOne) AddInputPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.AddInputPriceMicros(v)
	return _u
}

// SetOutputPriceMicros sets the "output_price_micros" field.
func (_u *UpstreamModelUpdateOne) SetOutputPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.ResetOutputPriceMicros()
	_u.mutation.SetOutputPriceMicros(v)
	return _u
}

// SetNillableOutputPriceMicros sets the "output_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableOutputPriceMicros(v *int64) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetOutputPriceMicros(*v)
	}
	return _u
}

// AddOutputPriceMicros adds value to the "output_price_micros" field.
func (_u *UpstreamModelUpdateOne) AddOutputPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.AddOutputPriceMicros(v)
	return _u
}

// SetCacheReadPriceMicros sets the "cache_read_price_micros" field.
func (_u *UpstreamModelUpdateOne) SetCacheReadPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.ResetCacheReadPriceMicros()
	_u.mutation.SetCacheReadPriceMicros(v)
	return _u
}

// SetNillableCacheReadPriceMicros sets the "cache_read_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableCacheReadPriceMicros(v *int64) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetCacheReadPriceMicros(*v)
	}
	return _u
}

// AddCacheReadPriceMicros adds value to the "cache_read_price_micros" field.
func (_u *UpstreamModelUpdateOne) AddCacheReadPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.AddCacheReadPriceMicros(v)
	return _u
}

// SetCacheWritePriceMicros sets the "cache_write_price_micros" field.
func (_u *UpstreamModelUpdateOne) SetCacheWritePriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.ResetCacheWritePriceMicros()
	_u.mutation.SetCacheWritePriceMicros(v)
	return _u
}

// SetNillableCacheWritePriceMicros sets the "cache_write_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableCacheWritePriceMicros(v *int64) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetCacheWritePriceMicros(*v)
	}
	return _u
}

// AddCacheWritePriceMicros adds value to the "cache_write_price_micros" field.
func (_u *UpstreamModelUpdateOne) AddCacheWritePriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.AddCacheWritePriceMicros(v)
	return _u
}

// SetCacheWrite1hPriceMicros sets the "cache_write_1h_price_micros" field.
func (_u *UpstreamModelUpdateOne) SetCacheWrite1hPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.ResetCacheWrite1hPriceMicros()
	_u.mutation.SetCacheWrite1hPriceMicros(v)
	return _u
}

// SetNillableCacheWrite1hPriceMicros sets the "cache_write_1h_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableCacheWrite1hPriceMicros(v *int64) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetCacheWrite1hPriceMicros(*v)
	}
	return _u
}

// AddCacheWrite1hPriceMicros adds value to the "cache_write_1h_price_micros" field.
func (_u *UpstreamModelUpdateOne) AddCacheWrite1hPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.AddCacheWrite1hPriceMicros(v)
	return _u
}

// SetRequestPriceMicros sets the "request_price_micros" field.
func (_u *UpstreamModelUpdateOne) SetRequestPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.ResetRequestPriceMicros()
	_u.mutation.SetRequestPriceMicros(v)
	return _u
}

// SetNillableRequestPriceMicros sets the "request_price_micros" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableRequestPriceMicros(v *int64) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetRequestPriceMicros(*v)
	}
	return _u
}

// AddRequestPriceMicros adds value to the "request_price_micros" field.
func (_u *UpstreamModelUpdateOne) AddRequestPriceMicros(v int64) *UpstreamModelUpdateOne {
	_u.mutation.AddRequestPriceMicros(v)
	return _u
}

// SetPricingConfigured sets the "pricing_configured" field.
func (_u *UpstreamModelUpdateOne) SetPricingConfigured(v bool) *UpstreamModelUpdateOne {
	_u.mutation.SetPricingConfigured(v)
	return _u
}

// SetNillablePricingConfigured sets the "pricing_configured" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillablePricingConfigured(v *bool) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetPricingConfigured(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamModelUpdateOne) SetStatus(v upstreammodel.Status) *UpstreamModelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableStatus(v *upstreammodel.Status) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamModelUpdateOne) SetUpdatedAt(v time.Time) *UpstreamModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UpstreamModelUpdateOne) SetDeletedAt(v time.Time) *UpstreamModelUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UpstreamModelUpdateOne) SetNillableDeletedAt(v *time.Time) *UpstreamModelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UpstreamModelUpdateOne) ClearDeletedAt() *UpstreamModelUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddModelRouteIDs adds the "model_routes" edge to the ModelRoute entity by IDs.
func (_u *UpstreamModelUpdateOne) AddModelRouteIDs(ids ...uuid.UUID) *UpstreamModelUpdateOne {
	_u.mutation.AddModelRouteIDs(ids...)
	return _u
}

// AddModelRoutes adds the "model_routes" edges to the ModelRoute entity.
func (_u *UpstreamModelUpdateOne) AddModelRoutes(v ...*ModelRoute) *UpstreamModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelRouteIDs(ids...)
}

// AddAPIUsageIDs adds the "api_usages" edge to the APIUsage entity by IDs.
func (_u *UpstreamModelUpdateOne) AddAPIUsageIDs(ids ...uuid.UUID) *UpstreamModelUpdateOne {
	_u.mutation.AddAPIUsageIDs(ids...)
	return _u
}

// AddAPIUsages adds the "api_usages" edges to the APIUsage entity.
func (_u *UpstreamModelUpdateOne) AddAPIUsages(v ...*APIUsage) *UpstreamModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIUsageIDs(ids...)
}

// AddPricePlanIDs adds the "price_plans" edge to the ModelPricePlan entity by IDs.
func (_u *UpstreamModelUpdateOne) AddPricePlanIDs(ids ...uuid.UUID) *UpstreamModelUpdateOne {
	_u.mutation.AddPricePlanIDs(ids...)
	return _u
}

// AddPricePlans adds the "price_plans" edges to the ModelPricePlan entity.
func (_u *UpstreamModelUpdateOne) AddPricePlans(v ...*ModelPricePlan) *UpstreamModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPricePlanIDs(ids...)
}

// Mutation returns the UpstreamModelMutation object of the builder.
func (_u *UpstreamModelUpdateOne) Mutation() *UpstreamModelMutation {
	return _u.mutation
}

// ClearModelRoutes clears all "model_routes" edges to the ModelRoute entity.
func (_u *UpstreamModelUpdateOne) ClearModelRoutes() *UpstreamModelUpdateOne {
	_u.mutation.ClearModelRoutes()
	return _u
}

// RemoveModelRouteIDs removes the "model_routes" edge to ModelRoute entities by IDs.
func (_u *UpstreamModelUpdateOne) RemoveModelRouteIDs(ids ...uuid.UUID) *UpstreamModelUpdateOne {
	_u.mutation.RemoveModelRouteIDs(ids...)
	return _u
}

// RemoveModelRoutes removes "model_routes" edges to ModelRoute entities.
func (_u *UpstreamModelUpdateOne) RemoveModelRoutes(v ...*ModelRoute) *UpstreamModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelRouteIDs(ids...)
}

// ClearAPIUsages clears all "api_usages" edges to the APIUsage entity.
func (_u *UpstreamModelUpdateOne) ClearAPIUsages() *UpstreamModelUpdateOne {
	_u.mutation.ClearAPIUsages()
	return _u
}

// RemoveAPIUsageIDs removes the "api_usages" edge to APIUsage entities by IDs.
func (_u *UpstreamModelUpdateOne) RemoveAPIUsageIDs(ids ...uuid.UUID) *UpstreamModelUpdateOne {
	_u.mutation.RemoveAPIUsageIDs(ids...)
	return _u
}

// RemoveAPIUsages removes "api_usages" edges to APIUsage entities.
func (_u *UpstreamModelUpdateOne) RemoveAPIUsages(v ...*APIUsage) *UpstreamModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIUsageIDs(ids...)
}

// ClearPricePlans clears all "price_plans" edges to the ModelPricePlan entity.
func (_u *UpstreamModelUpdateOne) ClearPricePlans() *UpstreamModelUpdateOne {
	_u.mutation.ClearPricePlans()
	return _u
}

// RemovePricePlanIDs removes the "price_plans" edge to ModelPricePlan entities by IDs.
func (_u *UpstreamModelUpdateOne) RemovePricePlanIDs(ids ...uuid.UUID) *UpstreamModelUpdateOne {
	_u.mutation.RemovePricePlanIDs(ids...)
	return _u
}

// RemovePricePlans removes "price_plans" edges to ModelPricePlan entities.
func (_u *UpstreamModelUpdateOne) RemovePricePlans(v ...*ModelPricePlan) *UpstreamModelUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePricePlanIDs(ids...)
}

// Where appends a list predicates to the UpstreamModelUpdate builder.
func (_u *UpstreamModelUpdateOne) Where(ps ...predicate.UpstreamModel) *UpstreamModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamModelUpdateOne) Select(field string, fields ...string) *UpstreamModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamModel entity.
func (_u *UpstreamModelUpdateOne) Save(ctx context.Context) (*UpstreamModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamModelUpdateOne) SaveX(ctx context.Context) *UpstreamModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreammodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamModelUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderName(); ok {
		if err := upstreammodel.ProviderNameValidator(v); err != nil {
			return &ValidationError{Name: "provider_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.provider_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamName(); ok {
		if err := upstreammodel.UpstreamNameValidator(v); err != nil {
			return &ValidationError{Name: "upstream_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.upstream_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := upstreammodel.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InputPriceMicros(); ok {
		if err := upstreammodel.InputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "input_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.input_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OutputPriceMicros(); ok {
		if err := upstreammodel.OutputPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "output_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.output_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheReadPriceMicros(); ok {
		if err := upstreammodel.CacheReadPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_read_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.cache_read_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheWritePriceMicros(); ok {
		if err := upstreammodel.CacheWritePriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_write_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.cache_write_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheWrite1hPriceMicros(); ok {
		if err := upstreammodel.CacheWrite1hPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "cache_write_1h_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.cache_write_1h_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestPriceMicros(); ok {
		if err := upstreammodel.RequestPriceMicrosValidator(v); err != nil {
			return &ValidationError{Name: "request_price_micros", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.request_price_micros": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreammodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamModel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamModelUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreammodel.Table, upstreammodel.Columns, sqlgraph.NewFieldSpec(upstreammodel.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreammodel.FieldID)
		for _, f := range fields {
			if !upstreammodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreammodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderName(); ok {
		_spec.SetField(upstreammodel.FieldProviderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamName(); ok {
		_spec.SetField(upstreammodel.FieldUpstreamName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(upstreammodel.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldInputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldInputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldOutputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldOutputPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldCacheReadPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldCacheReadPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWritePriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldCacheWritePriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldCacheWritePriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWrite1hPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldCacheWrite1hPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWrite1hPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldCacheWrite1hPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequestPriceMicros(); ok {
		_spec.SetField(upstreammodel.FieldRequestPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequestPriceMicros(); ok {
		_spec.AddField(upstreammodel.FieldRequestPriceMicros, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PricingConfigured(); ok {
		_spec.SetField(upstreammodel.FieldPricingConfigured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreammodel.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreammodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(upstreammodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(upstreammodel.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.ModelRoutesTable,
			Columns: []string{upstreammodel.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelRoutesIDs(); len(nodes) > 0 && !_u.mutation.ModelRoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.ModelRoutesTable,
			Columns: []string{upstreammodel.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelRoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.ModelRoutesTable,
			Columns: []string{upstreammodel.ModelRoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelroute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIUsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.APIUsagesTable,
			Columns: []string{upstreammodel.APIUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIUsagesIDs(); len(nodes) > 0 && !_u.mutation.APIUsagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.APIUsagesTable,
			Columns: []string{upstreammodel.APIUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIUsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.APIUsagesTable,
			Columns: []string{upstreammodel.APIUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PricePlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.PricePlansTable,
			Columns: []string{upstreammodel.PricePlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpriceplan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricePlansIDs(); len(nodes) > 0 && !_u.mutation.PricePlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.PricePlansTable,
			Columns: []string{upstreammodel.PricePlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpriceplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricePlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreammodel.PricePlansTable,
			Columns: []string{upstreammodel.PricePlansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpriceplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreammodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
