// Code generated by ent, DO NOT EDIT.

package walletentry

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the walletentry type in the database.
	Label = "wallet_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWalletID holds the string denoting the wallet_id field in the database.
	FieldWalletID = "wallet_id"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldReferenceID holds the string denoting the reference_id field in the database.
	FieldReferenceID = "reference_id"
	// FieldEntryType holds the string denoting the entry_type field in the database.
	FieldEntryType = "entry_type"
	// FieldAmountMicros holds the string denoting the amount_micros field in the database.
	FieldAmountMicros = "amount_micros"
	// FieldBalanceAfterMicros holds the string denoting the balance_after_micros field in the database.
	FieldBalanceAfterMicros = "balance_after_micros"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeWallet holds the string denoting the wallet edge name in mutations.
	EdgeWallet = "wallet"
	// EdgeActor holds the string denoting the actor edge name in mutations.
	EdgeActor = "actor"
	// Table holds the table name of the walletentry in the database.
	Table = "wallet_entries"
	// WalletTable is the table that holds the wallet relation/edge.
	WalletTable = "wallet_entries"
	// WalletInverseTable is the table name for the Wallet entity.
	// It exists in this package in order to avoid circular dependency with the "wallet" package.
	WalletInverseTable = "wallets"
	// WalletColumn is the table column denoting the wallet relation/edge.
	WalletColumn = "wallet_id"
	// ActorTable is the table that holds the actor relation/edge.
	ActorTable = "wallet_entries"
	// ActorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ActorInverseTable = "users"
	// ActorColumn is the table column denoting the actor relation/edge.
	ActorColumn = "actor_user_id"
)

// Columns holds all SQL columns for walletentry fields.
var Columns = []string{
	FieldID,
	FieldWalletID,
	FieldActorUserID,
	FieldReferenceID,
	FieldEntryType,
	FieldAmountMicros,
	FieldBalanceAfterMicros,
	FieldDescription,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BalanceAfterMicrosValidator is a validator for the "balance_after_micros" field. It is called by the builders before save.
	BalanceAfterMicrosValidator func(int64) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// EntryType defines the type for the "entry_type" enum field.
type EntryType string

// EntryType values.
const (
	EntryTypeManualAdjustment EntryType = "manual_adjustment"
	EntryTypeUsageReservation EntryType = "usage_reservation"
	EntryTypeUsageRefund      EntryType = "usage_refund"
)

func (et EntryType) String() string {
	return string(et)
}

// EntryTypeValidator is a validator for the "entry_type" field enum values. It is called by the builders before save.
func EntryTypeValidator(et EntryType) error {
	switch et {
	case EntryTypeManualAdjustment, EntryTypeUsageReservation, EntryTypeUsageRefund:
		return nil
	default:
		return fmt.Errorf("walletentry: invalid enum value for entry_type field: %q", et)
	}
}

// OrderOption defines the ordering options for the WalletEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWalletID orders the results by the wallet_id field.
func ByWalletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletID, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByReferenceID orders the results by the reference_id field.
func ByReferenceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceID, opts...).ToFunc()
}

// ByEntryType orders the results by the entry_type field.
func ByEntryType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryType, opts...).ToFunc()
}

// ByAmountMicros orders the results by the amount_micros field.
func ByAmountMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountMicros, opts...).ToFunc()
}

// ByBalanceAfterMicros orders the results by the balance_after_micros field.
func ByBalanceAfterMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfterMicros, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByWalletField orders the results by wallet field.
func ByWalletField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWalletStep(), sql.OrderByField(field, opts...))
	}
}

// ByActorField orders the results by actor field.
func ByActorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newActorStep(), sql.OrderByField(field, opts...))
	}
}
func newWalletStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WalletInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WalletTable, WalletColumn),
	)
}
func newActorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ActorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ActorTable, ActorColumn),
	)
}
