// Code generated by ent, DO NOT EDIT.

package topuporder

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the topuporder type in the database.
	Label = "top_up_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOutTradeNo holds the string denoting the out_trade_no field in the database.
	FieldOutTradeNo = "out_trade_no"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldAmountMicros holds the string denoting the amount_micros field in the database.
	FieldAmountMicros = "amount_micros"
	// FieldCreditedMicros holds the string denoting the credited_micros field in the database.
	FieldCreditedMicros = "credited_micros"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProviderTradeNo holds the string denoting the provider_trade_no field in the database.
	FieldProviderTradeNo = "provider_trade_no"
	// FieldPaidAt holds the string denoting the paid_at field in the database.
	FieldPaidAt = "paid_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the topuporder in the database.
	Table = "top_up_orders"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "top_up_orders"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for topuporder fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldOutTradeNo,
	FieldProvider,
	FieldChannel,
	FieldAmountMicros,
	FieldCreditedMicros,
	FieldStatus,
	FieldProviderTradeNo,
	FieldPaidAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OutTradeNoValidator is a validator for the "out_trade_no" field. It is called by the builders before save.
	OutTradeNoValidator func(string) error
	// ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	ChannelValidator func(string) error
	// AmountMicrosValidator is a validator for the "amount_micros" field. It is called by the builders before save.
	AmountMicrosValidator func(int64) error
	// CreditedMicrosValidator is a validator for the "credited_micros" field. It is called by the builders before save.
	CreditedMicrosValidator func(int64) error
	// ProviderTradeNoValidator is a validator for the "provider_trade_no" field. It is called by the builders before save.
	ProviderTradeNoValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Provider defines the type for the "provider" enum field.
type Provider string

// ProviderEpay is the default value of the Provider enum.
const DefaultProvider = ProviderEpay

// Provider values.
const (
	ProviderEpay Provider = "epay"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderEpay:
		return nil
	default:
		return fmt.Errorf("topuporder: invalid enum value for provider field: %q", pr)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending Status = "pending"
	StatusPaid    Status = "paid"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusPaid:
		return nil
	default:
		return fmt.Errorf("topuporder: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the TopUpOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOutTradeNo orders the results by the out_trade_no field.
func ByOutTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutTradeNo, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByAmountMicros orders the results by the amount_micros field.
func ByAmountMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountMicros, opts...).ToFunc()
}

// ByCreditedMicros orders the results by the credited_micros field.
func ByCreditedMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditedMicros, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProviderTradeNo orders the results by the provider_trade_no field.
func ByProviderTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderTradeNo, opts...).ToFunc()
}

// ByPaidAt orders the results by the paid_at field.
func ByPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaidAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
