// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviteCode holds the string denoting the invite_code field in the database.
	FieldInviteCode = "invite_code"
	// FieldReferredByUserID holds the string denoting the referred_by_user_id field in the database.
	FieldReferredByUserID = "referred_by_user_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldIsSystemAdmin holds the string denoting the is_system_admin field in the database.
	FieldIsSystemAdmin = "is_system_admin"
	// FieldCanAccessHiddenGroups holds the string denoting the can_access_hidden_groups field in the database.
	FieldCanAccessHiddenGroups = "can_access_hidden_groups"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeIdentities holds the string denoting the identities edge name in mutations.
	EdgeIdentities = "identities"
	// EdgeAPIKeys holds the string denoting the api_keys edge name in mutations.
	EdgeAPIKeys = "api_keys"
	// EdgeWallet holds the string denoting the wallet edge name in mutations.
	EdgeWallet = "wallet"
	// EdgeWalletEntries holds the string denoting the wallet_entries edge name in mutations.
	EdgeWalletEntries = "wallet_entries"
	// EdgeTopUpOrders holds the string denoting the top_up_orders edge name in mutations.
	EdgeTopUpOrders = "top_up_orders"
	// EdgeAPIUsages holds the string denoting the api_usages edge name in mutations.
	EdgeAPIUsages = "api_usages"
	// EdgeGatewayOperations holds the string denoting the gateway_operations edge name in mutations.
	EdgeGatewayOperations = "gateway_operations"
	// EdgeReferrer holds the string denoting the referrer edge name in mutations.
	EdgeReferrer = "referrer"
	// EdgeReferrals holds the string denoting the referrals edge name in mutations.
	EdgeReferrals = "referrals"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "user_sessions"
	// SessionsInverseTable is the table name for the UserSession entity.
	// It exists in this package in order to avoid circular dependency with the "usersession" package.
	SessionsInverseTable = "user_sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "user_id"
	// IdentitiesTable is the table that holds the identities relation/edge.
	IdentitiesTable = "user_identities"
	// IdentitiesInverseTable is the table name for the UserIdentity entity.
	// It exists in this package in order to avoid circular dependency with the "useridentity" package.
	IdentitiesInverseTable = "user_identities"
	// IdentitiesColumn is the table column denoting the identities relation/edge.
	IdentitiesColumn = "user_id"
	// APIKeysTable is the table that holds the api_keys relation/edge.
	APIKeysTable = "api_keys"
	// APIKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeysInverseTable = "api_keys"
	// APIKeysColumn is the table column denoting the api_keys relation/edge.
	APIKeysColumn = "user_id"
	// WalletTable is the table that holds the wallet relation/edge.
	WalletTable = "wallets"
	// WalletInverseTable is the table name for the Wallet entity.
	// It exists in this package in order to avoid circular dependency with the "wallet" package.
	WalletInverseTable = "wallets"
	// WalletColumn is the table column denoting the wallet relation/edge.
	WalletColumn = "user_id"
	// WalletEntriesTable is the table that holds the wallet_entries relation/edge.
	WalletEntriesTable = "wallet_entries"
	// WalletEntriesInverseTable is the table name for the WalletEntry entity.
	// It exists in this package in order to avoid circular dependency with the "walletentry" package.
	WalletEntriesInverseTable = "wallet_entries"
	// WalletEntriesColumn is the table column denoting the wallet_entries relation/edge.
	WalletEntriesColumn = "actor_user_id"
	// TopUpOrdersTable is the table that holds the top_up_orders relation/edge.
	TopUpOrdersTable = "top_up_orders"
	// TopUpOrdersInverseTable is the table name for the TopUpOrder entity.
	// It exists in this package in order to avoid circular dependency with the "topuporder" package.
	TopUpOrdersInverseTable = "top_up_orders"
	// TopUpOrdersColumn is the table column denoting the top_up_orders relation/edge.
	TopUpOrdersColumn = "user_id"
	// APIUsagesTable is the table that holds the api_usages relation/edge.
	APIUsagesTable = "api_usages"
	// APIUsagesInverseTable is the table name for the APIUsage entity.
	// It exists in this package in order to avoid circular dependency with the "apiusage" package.
	APIUsagesInverseTable = "api_usages"
	// APIUsagesColumn is the table column denoting the api_usages relation/edge.
	APIUsagesColumn = "user_id"
	// GatewayOperationsTable is the table that holds the gateway_operations relation/edge.
	GatewayOperationsTable = "gateway_operations"
	// GatewayOperationsInverseTable is the table name for the GatewayOperation entity.
	// It exists in this package in order to avoid circular dependency with the "gatewayoperation" package.
	GatewayOperationsInverseTable = "gateway_operations"
	// GatewayOperationsColumn is the table column denoting the gateway_operations relation/edge.
	GatewayOperationsColumn = "user_id"
	// ReferrerTable is the table that holds the referrer relation/edge.
	ReferrerTable = "users"
	// ReferrerColumn is the table column denoting the referrer relation/edge.
	ReferrerColumn = "referred_by_user_id"
	// ReferralsTable is the table that holds the referrals relation/edge.
	ReferralsTable = "users"
	// ReferralsColumn is the table column denoting the referrals relation/edge.
	ReferralsColumn = "referred_by_user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldInviteCode,
	FieldReferredByUserID,
	FieldUsername,
	FieldEmail,
	FieldDisplayName,
	FieldPasswordHash,
	FieldIsSystemAdmin,
	FieldCanAccessHiddenGroups,
	FieldRole,
	FieldStatus,
	FieldLastLoginAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultInviteCode holds the default value on creation for the "invite_code" field.
	DefaultInviteCode func() string
	// InviteCodeValidator is a validator for the "invite_code" field. It is called by the builders before save.
	InviteCodeValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultDisplayName holds the default value on creation for the "display_name" field.
	DefaultDisplayName string
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultIsSystemAdmin holds the default value on creation for the "is_system_admin" field.
	DefaultIsSystemAdmin bool
	// DefaultCanAccessHiddenGroups holds the default value on creation for the "can_access_hidden_groups" field.
	DefaultCanAccessHiddenGroups bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Role defines the type for the "role" enum field.
type Role string

// RoleMember is the default value of the Role enum.
const DefaultRole = RoleMember

// Role values.
const (
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleAdmin, RoleMember:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive   Status = "active"
	StatusDisabled Status = "disabled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusDisabled:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviteCode orders the results by the invite_code field.
func ByInviteCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteCode, opts...).ToFunc()
}

// ByReferredByUserID orders the results by the referred_by_user_id field.
func ByReferredByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferredByUserID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByIsSystemAdmin orders the results by the is_system_admin field.
func ByIsSystemAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSystemAdmin, opts...).ToFunc()
}

// ByCanAccessHiddenGroups orders the results by the can_access_hidden_groups field.
func ByCanAccessHiddenGroups(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanAccessHiddenGroups, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIdentitiesCount orders the results by identities count.
func ByIdentitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIdentitiesStep(), opts...)
	}
}

// ByIdentities orders the results by identities terms.
func ByIdentities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIdentitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAPIKeysCount orders the results by api_keys count.
func ByAPIKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIKeysStep(), opts...)
	}
}

// ByAPIKeys orders the results by api_keys terms.
func ByAPIKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWalletField orders the results by wallet field.
func ByWalletField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWalletStep(), sql.OrderByField(field, opts...))
	}
}

// ByWalletEntriesCount orders the results by wallet_entries count.
func ByWalletEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWalletEntriesStep(), opts...)
	}
}

// ByWalletEntries orders the results by wallet_entries terms.
func ByWalletEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWalletEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTopUpOrdersCount orders the results by top_up_orders count.
func ByTopUpOrdersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTopUpOrdersStep(), opts...)
	}
}

// ByTopUpOrders orders the results by top_up_orders terms.
func ByTopUpOrders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTopUpOrdersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAPIUsagesCount orders the results by api_usages count.
func ByAPIUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPIUsagesStep(), opts...)
	}
}

// ByAPIUsages orders the results by api_usages terms.
func ByAPIUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGatewayOperationsCount orders the results by gateway_operations count.
func ByGatewayOperationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGatewayOperationsStep(), opts...)
	}
}

// ByGatewayOperations orders the results by gateway_operations terms.
func ByGatewayOperations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGatewayOperationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReferrerField orders the results by referrer field.
func ByReferrerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferrerStep(), sql.OrderByField(field, opts...))
	}
}

// ByReferralsCount orders the results by referrals count.
func ByReferralsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReferralsStep(), opts...)
	}
}

// ByReferrals orders the results by referrals terms.
func ByReferrals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferralsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newIdentitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IdentitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IdentitiesTable, IdentitiesColumn),
	)
}
func newAPIKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
	)
}
func newWalletStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WalletInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, WalletTable, WalletColumn),
	)
}
func newWalletEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WalletEntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WalletEntriesTable, WalletEntriesColumn),
	)
}
func newTopUpOrdersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TopUpOrdersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TopUpOrdersTable, TopUpOrdersColumn),
	)
}
func newAPIUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIUsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APIUsagesTable, APIUsagesColumn),
	)
}
func newGatewayOperationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GatewayOperationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, GatewayOperationsTable, GatewayOperationsColumn),
	)
}
func newReferrerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
	)
}
func newReferralsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(Table, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ReferralsTable, ReferralsColumn),
	)
}
